<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="docker_plugin_remove" skipped="0" tests="1" time="4.61" timestamp="2022-05-02T16:01:02">
	<testcase classname="DockerPluginRemoveTest" name="docker_plugin_remove">
		<failure message="BLOCKED: sudo&lt;docker_run&gt; returned non-zero exit code 125" type="BLOCKED"/>
		<system-out>16:00:57 INFO  ==============================================================
16:00:57 INFO  Id:    docker_plugin_remove
16:00:57 INFO  Dir:   plugin_docker/
16:00:57 INFO  Title: Validate docker plugin remove
16:00:57 INFO  ==============================================================
16:00:58 INFO  Executed sudo&lt;docker_images&gt;, exit status 0
16:00:58 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_remove/Output/linux/docker_images.out ... passed
16:01:00 WARN  Executed sudo&lt;docker_run&gt;, exit status 125
16:01:00 INFO  Contents of docker_run.err: 
  Unable to find image 'registry:latest' locally
  docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
  See 'docker run --help'.
  -----

16:01:00 WARN  sudo&lt;docker_run&gt; returned non-zero exit code 125 ... blocked 
16:01:00 WARN  Aborted test due to BLOCKED outcome
16:01:00 INFO  
16:01:00 INFO  cleanup:
16:01:00 INFO  Removing containers scheduled to be cleaned up: ['', '']
16:01:01 WARN  Executed sudo&lt;containers_for_cleanup&gt;, exit status 1
16:01:01 INFO  Removing images scheduled to be cleaned up: ['registry', 'registry:2.7.1']
16:01:02 INFO  Executed sudo&lt;containers_for_cleanup&gt;, exit status 0
16:01:02 INFO  
16:01:02 INFO  Test duration: 4.61 secs
16:01:02 INFO  Test final outcome:  BLOCKED
16:01:02 INFO  Test outcome reason: sudo&lt;docker_run&gt; returned non-zero exit code 125
16:01:02 INFO  
</system-out>
	</testcase>
</testsuite>
