<?xml version='1.0' encoding='utf-8'?>
<testsuites tests="152" failures="36" errors="0" skipped="0" time="0.0"><testsuite name="SoftwareManagement.sm_apt_install_download_path" tests="4" errors="0" failures="4" skipped="0" time="0"><testcase classname="AptInstallWithDownloadPath" name="SoftwareManagement.sm_apt_install_download_path">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED" />
		<system-out>10:22:08 INFO  ==============================================================
10:22:08 INFO  Id:    SoftwareManagement.sm_apt_install_download_path
10:22:08 INFO  Dir:   software_management_end_to_end/
10:22:08 INFO  Title: Install package to directory specified in tedge config set tmp.path
10:22:08 INFO  ==============================================================
10:22:08 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:22:08 INFO  EnvironmentC8y Setup
10:22:09 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:22:24 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
10:22:26 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:22:28 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:22:28 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:22:31 ERROR No operations found, assuming it passed
10:22:31 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_download_path/run.py", line 49, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
10:22:31 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
10:22:31 INFO  
10:22:31 INFO  cleanup:
10:22:32 INFO  Executed sudo, exit status 0
10:22:33 INFO  Executed sudo, exit status 0
10:22:37 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:22:37 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 3 seconds
10:22:37 INFO  Delaying execution by 8 seconds
10:22:59 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
10:23:03 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:23:04 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:23:04 INFO  
10:23:04 INFO  Test duration: 56.39 secs
10:23:04 INFO  Test final outcome:  BLOCKED
10:23:04 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
10:23:04 INFO  
</system-out>
	</testcase>
<testcase classname="AptInstallWithDownloadPath" name="SoftwareManagement.sm_apt_install_download_path">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED" />
		<system-out>10:22:08 INFO  ==============================================================
10:22:08 INFO  Id:    SoftwareManagement.sm_apt_install_download_path
10:22:08 INFO  Dir:   software_management_end_to_end/
10:22:08 INFO  Title: Install package to directory specified in tedge config set tmp.path
10:22:08 INFO  ==============================================================
10:22:08 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:22:08 INFO  EnvironmentC8y Setup
10:22:09 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:22:24 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
10:22:25 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:22:26 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:22:27 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:22:29 ERROR No operations found, assuming it passed
10:22:30 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_download_path/run.py", line 49, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
10:22:30 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
10:22:30 INFO  
10:22:30 INFO  cleanup:
10:22:31 INFO  Executed sudo, exit status 0
10:22:31 INFO  Executed sudo, exit status 0
10:22:35 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:22:35 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 3 seconds
10:22:35 INFO  Delaying execution by 8 seconds
10:22:57 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
10:23:02 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:23:02 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:23:02 INFO  
10:23:02 INFO  Test duration: 54.36 secs
10:23:02 INFO  Test final outcome:  BLOCKED
10:23:02 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
10:23:02 INFO  
</system-out>
	</testcase>
<testcase classname="AptInstallWithDownloadPath" name="SoftwareManagement.sm_apt_install_download_path">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED" />
		<system-out>10:22:08 INFO  ==============================================================
10:22:08 INFO  Id:    SoftwareManagement.sm_apt_install_download_path
10:22:08 INFO  Dir:   software_management_end_to_end/
10:22:08 INFO  Title: Install package to directory specified in tedge config set tmp.path
10:22:08 INFO  ==============================================================
10:22:08 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:22:08 INFO  EnvironmentC8y Setup
10:22:09 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:22:23 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
10:22:25 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:22:26 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:22:27 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:22:29 ERROR No operations found, assuming it passed
10:22:29 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_download_path/run.py", line 49, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
10:22:30 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
10:22:30 INFO  
10:22:30 INFO  cleanup:
10:22:30 INFO  Executed sudo, exit status 0
10:22:31 INFO  Executed sudo, exit status 0
10:22:35 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:22:35 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 3 seconds
10:22:35 INFO  Delaying execution by 8 seconds
10:22:57 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
10:23:01 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:23:02 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:23:02 INFO  
10:23:02 INFO  Test duration: 54.14 secs
10:23:02 INFO  Test final outcome:  BLOCKED
10:23:02 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
10:23:02 INFO  
</system-out>
	</testcase>
<testcase classname="AptInstallWithDownloadPath" name="SoftwareManagement.sm_apt_install_download_path">
		<failure message="BLOCKED: AssertionError:" type="BLOCKED" />
		<system-out>10:43:38 INFO  ==============================================================
10:43:38 INFO  Id:    SoftwareManagement.sm_apt_install_download_path
10:43:38 INFO  Dir:   software_management_end_to_end/
10:43:38 INFO  Title: Install package to directory specified in tedge config set tmp.path
10:43:38 INFO  ==============================================================
10:43:38 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:43:38 INFO  EnvironmentC8y Setup
10:43:39 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:43:53 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
10:43:55 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:43:56 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:43:57 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:43:59 INFO  State of current operation: SUCCESSFUL
10:43:59 INFO  Assert that (False == value) with value=False ... passed
10:44:00 INFO  Executed sudo, exit status 0
10:44:00 INFO  Executed sudo, exit status 0
10:44:01 INFO  Executed sudo, exit status 0
10:44:05 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:44:05 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 3 seconds
10:44:05 INFO  Delaying execution by 8 seconds
10:44:27 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
10:44:27 INFO  Response status: 201
10:44:27 INFO  Response to action: {
    "delivery": {
        "time": "2022-04-14T10:44:27.380Z",
        "log": [],
        "status": "PENDING"
    },
    "creationTime": "2022-04-14T10:44:27.365Z",
    "deviceName": "mythicd",
    "deviceId": "17331100",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17330331",
    "id": "17330331",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'name': 'rolldice', 'id': '5152439', 'version': '::apt', 'url': 'https://thin-edge-io.eu-latest.cumulocity.com/inventory/binaries/12435463', 'action': 'install'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "rolldice",
            "action": "install",
            "id": "5152439",
            "version": "::apt",
            "url": "https://thin-edge-io.eu-latest.cumulocity.com/inventory/binaries/12435463"
        }
    ]
}
10:44:27 INFO  Started operation: {'delivery': {'time': '2022-04-14T10:44:27.380Z', 'log': [], 'status': 'PENDING'}, 'creationTime': '2022-04-14T10:44:27.365Z', 'deviceName': 'mythicd', 'deviceId': '17331100', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17330331', 'id': '17330331', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'name': 'rolldice', 'id': '5152439', 'version': '::apt', 'url': 'https://thin-edge-io.eu-latest.cumulocity.com/inventory/binaries/12435463', 'action': 'install'}]", 'c8y_SoftwareUpdate': [{'name': 'rolldice', 'action': 'install', 'id': '5152439', 'version': '::apt', 'url': 'https://thin-edge-io.eu-latest.cumulocity.com/inventory/binaries/12435463'}]}
10:44:27 WARN  , retrying in 0.5 seconds...
10:44:27 WARN  , retrying in 0.5 seconds...
10:44:28 WARN  , retrying in 0.5 seconds...
10:44:28 WARN  , retrying in 0.5 seconds...
10:44:29 WARN  , retrying in 0.5 seconds...
10:44:29 WARN  , retrying in 0.5 seconds...
10:44:30 WARN  , retrying in 0.5 seconds...
10:44:30 WARN  , retrying in 0.5 seconds...
10:44:31 WARN  , retrying in 0.5 seconds...
10:44:31 WARN  AssertionError occurred while running test - 
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1294, in __call__
    self.testObj.execute()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_download_path/run.py", line 83, in execute
    assert_install_in_download_path(install_directory=self.DOWNLOAD_DIR)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_download_path/run.py", line 28, in assert_install_in_download_path
    assert "rolldice" in os.listdir(f"{install_directory}")
AssertionError
10:44:32 WARN  AssertionError: ... blocked 
10:44:32 INFO  
10:44:32 INFO  cleanup:
10:44:33 INFO  Executed sudo, exit status 0
10:44:33 INFO  Executed sudo, exit status 0
10:44:38 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:44:38 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 3 seconds
10:44:38 INFO  Delaying execution by 8 seconds
10:45:00 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
10:45:04 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:45:05 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:45:05 INFO  
10:45:05 INFO  Test duration: 86.83 secs
10:45:05 INFO  Test final outcome:  BLOCKED
10:45:05 INFO  Test outcome reason: AssertionError:
10:45:05 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_apt_install_fail" tests="4" errors="0" failures="3" skipped="0" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_fail">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED" />
		<system-out>10:23:04 INFO  ==============================================================
10:23:04 INFO  Id:    SoftwareManagement.sm_apt_install_fail
10:23:04 INFO  Dir:   software_management_end_to_end/
10:23:04 INFO  Title: Validate end to end behaviour for a failing installation
10:23:04 INFO  ==============================================================
10:23:04 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:23:04 INFO  EnvironmentC8y Setup
10:23:05 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:23:05 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
10:23:05 INFO  Delaying execution by 6 seconds
10:23:26 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
10:23:26 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:23:27 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:23:27 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:23:29 ERROR No operations found, assuming it passed
10:23:30 INFO  Response status: 201
10:23:30 INFO  Response to action: {
    "creationTime": "2022-04-14T10:23:30.173Z",
    "deviceName": "mythica",
    "deviceId": "17326138",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17330316",
    "id": "17330316",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'name': 'does_not_exist', 'id': '5446165', 'version': '::apt', 'url': '', 'action': 'install'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "does_not_exist",
            "action": "install",
            "id": "5446165",
            "version": "::apt",
            "url": ""
        }
    ]
}
10:23:30 INFO  Started operation: {'creationTime': '2022-04-14T10:23:30.173Z', 'deviceName': 'mythica', 'deviceId': '17326138', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17330316', 'id': '17330316', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'name': 'does_not_exist', 'id': '5446165', 'version': '::apt', 'url': '', 'action': 'install'}]", 'c8y_SoftwareUpdate': [{'name': 'does_not_exist', 'action': 'install', 'id': '5446165', 'version': '::apt', 'url': ''}]}
10:23:32 INFO  State of operation 17330316 : PENDING
10:23:34 INFO  State of operation 17330316 : EXECUTING
10:23:36 INFO  State of operation 17330316 : EXECUTING
10:23:39 INFO  State of operation 17330316 : EXECUTING
10:23:41 INFO  State of operation 17330316 : EXECUTING
10:23:43 INFO  State of operation 17330316 : EXECUTING
10:23:46 INFO  State of operation 17330316 : EXECUTING
10:23:48 INFO  State of operation 17330316 : EXECUTING
10:23:51 INFO  State of operation 17330316 : EXECUTING
10:23:53 INFO  State of operation 17330316 : EXECUTING
10:23:55 INFO  State of operation 17330316 : EXECUTING
10:23:58 INFO  State of operation 17330316 : EXECUTING
10:24:00 INFO  State of operation 17330316 : EXECUTING
10:24:02 INFO  State of operation 17330316 : EXECUTING
10:24:04 INFO  State of operation 17330316 : EXECUTING
10:24:07 INFO  State of operation 17330316 : EXECUTING
10:24:09 INFO  State of operation 17330316 : EXECUTING
10:24:12 INFO  State of operation 17330316 : EXECUTING
10:24:14 INFO  State of operation 17330316 : EXECUTING
10:24:16 INFO  State of operation 17330316 : EXECUTING
10:24:19 INFO  State of operation 17330316 : FAILED
10:24:19 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1296, in __call__
    self.testObj.validate()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_fail/run.py", line 31, in validate
    "False == value", value=self.check_is_installed("does_not_exist")
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
10:24:19 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
10:24:19 INFO  
10:24:19 INFO  cleanup:
10:24:23 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:24:23 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:24:23 INFO  
10:24:23 INFO  Test duration: 79.44 secs
10:24:23 INFO  Test final outcome:  BLOCKED
10:24:23 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
10:24:23 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_fail">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED" />
		<system-out>10:23:03 INFO  ==============================================================
10:23:03 INFO  Id:    SoftwareManagement.sm_apt_install_fail
10:23:03 INFO  Dir:   software_management_end_to_end/
10:23:03 INFO  Title: Validate end to end behaviour for a failing installation
10:23:03 INFO  ==============================================================
10:23:03 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:23:03 INFO  EnvironmentC8y Setup
10:23:03 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:23:03 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
10:23:03 INFO  Delaying execution by 6 seconds
10:23:24 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 15 secs
10:23:25 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:23:25 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:23:26 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:23:28 ERROR No operations found, assuming it passed
10:23:28 INFO  Response status: 201
10:23:28 INFO  Response to action: {
    "delivery": {
        "time": "2022-04-14T10:23:28.739Z",
        "log": [],
        "status": "PENDING"
    },
    "creationTime": "2022-04-14T10:23:28.729Z",
    "deviceName": "mythicb",
    "deviceId": "17329985",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17330312",
    "id": "17330312",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'name': 'does_not_exist', 'id': '5446165', 'version': '::apt', 'url': '', 'action': 'install'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "does_not_exist",
            "action": "install",
            "id": "5446165",
            "version": "::apt",
            "url": ""
        }
    ]
}
10:23:28 INFO  Started operation: {'delivery': {'time': '2022-04-14T10:23:28.739Z', 'log': [], 'status': 'PENDING'}, 'creationTime': '2022-04-14T10:23:28.729Z', 'deviceName': 'mythicb', 'deviceId': '17329985', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17330312', 'id': '17330312', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'name': 'does_not_exist', 'id': '5446165', 'version': '::apt', 'url': '', 'action': 'install'}]", 'c8y_SoftwareUpdate': [{'name': 'does_not_exist', 'action': 'install', 'id': '5446165', 'version': '::apt', 'url': ''}]}
10:23:31 INFO  State of operation 17330312 : PENDING
10:23:33 INFO  State of operation 17330312 : EXECUTING
10:23:35 INFO  State of operation 17330312 : EXECUTING
10:23:37 INFO  State of operation 17330312 : EXECUTING
10:23:39 INFO  State of operation 17330312 : EXECUTING
10:23:42 INFO  State of operation 17330312 : EXECUTING
10:23:44 INFO  State of operation 17330312 : EXECUTING
10:23:47 INFO  State of operation 17330312 : EXECUTING
10:23:50 INFO  State of operation 17330312 : EXECUTING
10:23:52 INFO  State of operation 17330312 : EXECUTING
10:23:54 INFO  State of operation 17330312 : EXECUTING
10:23:56 INFO  State of operation 17330312 : EXECUTING
10:23:59 INFO  State of operation 17330312 : EXECUTING
10:24:01 INFO  State of operation 17330312 : EXECUTING
10:24:03 INFO  State of operation 17330312 : EXECUTING
10:24:05 INFO  State of operation 17330312 : EXECUTING
10:24:08 INFO  State of operation 17330312 : EXECUTING
10:24:11 INFO  State of operation 17330312 : EXECUTING
10:24:13 INFO  State of operation 17330312 : EXECUTING
10:24:15 INFO  State of operation 17330312 : EXECUTING
10:24:17 INFO  State of operation 17330312 : FAILED
10:24:18 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1296, in __call__
    self.testObj.validate()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_fail/run.py", line 31, in validate
    "False == value", value=self.check_is_installed("does_not_exist")
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
10:24:18 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
10:24:18 INFO  
10:24:18 INFO  cleanup:
10:24:22 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:24:23 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:24:23 INFO  
10:24:23 INFO  Test duration: 80.27 secs
10:24:23 INFO  Test final outcome:  BLOCKED
10:24:23 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
10:24:23 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_fail">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED" />
		<system-out>10:23:02 INFO  ==============================================================
10:23:02 INFO  Id:    SoftwareManagement.sm_apt_install_fail
10:23:02 INFO  Dir:   software_management_end_to_end/
10:23:02 INFO  Title: Validate end to end behaviour for a failing installation
10:23:02 INFO  ==============================================================
10:23:02 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:23:02 INFO  EnvironmentC8y Setup
10:23:03 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:23:03 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
10:23:03 INFO  Delaying execution by 6 seconds
10:23:22 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
10:23:23 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:23:24 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:23:24 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:23:26 ERROR No operations found, assuming it passed
10:23:27 INFO  Response status: 201
10:23:27 INFO  Response to action: {
    "creationTime": "2022-04-14T10:23:27.039Z",
    "deviceName": "mythicc",
    "deviceId": "17326137",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17330310",
    "id": "17330310",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'name': 'does_not_exist', 'id': '5446165', 'version': '::apt', 'url': '', 'action': 'install'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "does_not_exist",
            "action": "install",
            "id": "5446165",
            "version": "::apt",
            "url": ""
        }
    ]
}
10:23:27 INFO  Started operation: {'creationTime': '2022-04-14T10:23:27.039Z', 'deviceName': 'mythicc', 'deviceId': '17326137', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17330310', 'id': '17330310', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'name': 'does_not_exist', 'id': '5446165', 'version': '::apt', 'url': '', 'action': 'install'}]", 'c8y_SoftwareUpdate': [{'name': 'does_not_exist', 'action': 'install', 'id': '5446165', 'version': '::apt', 'url': ''}]}
10:23:29 INFO  State of operation 17330310 : PENDING
10:23:31 INFO  State of operation 17330310 : EXECUTING
10:23:33 INFO  State of operation 17330310 : EXECUTING
10:23:36 INFO  State of operation 17330310 : EXECUTING
10:23:38 INFO  State of operation 17330310 : EXECUTING
10:23:40 INFO  State of operation 17330310 : EXECUTING
10:23:42 INFO  State of operation 17330310 : EXECUTING
10:23:45 INFO  State of operation 17330310 : EXECUTING
10:23:48 INFO  State of operation 17330310 : EXECUTING
10:23:50 INFO  State of operation 17330310 : EXECUTING
10:23:52 INFO  State of operation 17330310 : EXECUTING
10:23:55 INFO  State of operation 17330310 : EXECUTING
10:23:57 INFO  State of operation 17330310 : EXECUTING
10:23:59 INFO  State of operation 17330310 : EXECUTING
10:24:01 INFO  State of operation 17330310 : EXECUTING
10:24:04 INFO  State of operation 17330310 : EXECUTING
10:24:06 INFO  State of operation 17330310 : EXECUTING
10:24:08 INFO  State of operation 17330310 : EXECUTING
10:24:11 INFO  State of operation 17330310 : EXECUTING
10:24:13 INFO  State of operation 17330310 : EXECUTING
10:24:16 INFO  State of operation 17330310 : FAILED
10:24:16 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1296, in __call__
    self.testObj.validate()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_fail/run.py", line 31, in validate
    "False == value", value=self.check_is_installed("does_not_exist")
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
10:24:16 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
10:24:16 INFO  
10:24:16 INFO  cleanup:
10:24:20 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:24:20 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:24:20 INFO  
10:24:20 INFO  Test duration: 78.39 secs
10:24:20 INFO  Test final outcome:  BLOCKED
10:24:20 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
10:24:20 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_fail" />
</testsuite><testsuite name="SoftwareManagement.sm_apt_install_remove" tests="4" errors="0" failures="3" skipped="0" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED" />
		<system-out>10:24:24 INFO  ==============================================================
10:24:24 INFO  Id:    SoftwareManagement.sm_apt_install_remove
10:24:24 INFO  Dir:   software_management_end_to_end/
10:24:24 INFO  Title: Validate end to end behaviour for the apt plugin for installation and removal of packages
10:24:24 INFO  ==============================================================
10:24:24 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:24:24 INFO  EnvironmentC8y Setup
10:24:24 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:24:24 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
10:24:24 INFO  Delaying execution by 6 seconds
10:24:45 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
10:24:45 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:24:46 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:24:46 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:24:49 INFO  State of current operation: FAILED
10:24:49 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove/run.py", line 28, in setup
    if self.check_is_installed("rolldice"):
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
10:24:49 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
10:24:49 INFO  
10:24:49 INFO  cleanup:
10:24:53 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:24:54 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:24:54 INFO  
10:24:54 INFO  Test duration: 30.13 secs
10:24:54 INFO  Test final outcome:  BLOCKED
10:24:54 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
10:24:54 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED" />
		<system-out>10:24:23 INFO  ==============================================================
10:24:23 INFO  Id:    SoftwareManagement.sm_apt_install_remove
10:24:23 INFO  Dir:   software_management_end_to_end/
10:24:23 INFO  Title: Validate end to end behaviour for the apt plugin for installation and removal of packages
10:24:23 INFO  ==============================================================
10:24:23 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:24:23 INFO  EnvironmentC8y Setup
10:24:23 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:24:24 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 6 seconds
10:24:24 INFO  Delaying execution by 5 seconds
10:24:43 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
10:24:44 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:24:44 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:24:45 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:24:47 INFO  State of current operation: FAILED
10:24:47 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove/run.py", line 28, in setup
    if self.check_is_installed("rolldice"):
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
10:24:47 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
10:24:47 INFO  
10:24:47 INFO  cleanup:
10:24:52 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:24:52 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:24:52 INFO  
10:24:52 INFO  Test duration: 29.28 secs
10:24:52 INFO  Test final outcome:  BLOCKED
10:24:52 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
10:24:52 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED" />
		<system-out>10:24:20 INFO  ==============================================================
10:24:20 INFO  Id:    SoftwareManagement.sm_apt_install_remove
10:24:20 INFO  Dir:   software_management_end_to_end/
10:24:20 INFO  Title: Validate end to end behaviour for the apt plugin for installation and removal of packages
10:24:20 INFO  ==============================================================
10:24:20 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:24:20 INFO  EnvironmentC8y Setup
10:24:21 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:24:21 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
10:24:21 INFO  Delaying execution by 7 seconds
10:24:42 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
10:24:43 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:24:43 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:24:44 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:24:46 INFO  State of current operation: FAILED
10:24:46 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove/run.py", line 28, in setup
    if self.check_is_installed("rolldice"):
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
10:24:46 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
10:24:46 INFO  
10:24:46 INFO  cleanup:
10:24:51 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:24:51 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:24:51 INFO  
10:24:51 INFO  Test duration: 30.61 secs
10:24:51 INFO  Test final outcome:  BLOCKED
10:24:51 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
10:24:51 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove" />
</testsuite><testsuite name="SoftwareManagement.sm_apt_install_remove_default" tests="4" errors="0" failures="3" skipped="0" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_default">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED" />
		<system-out>10:24:54 INFO  ==============================================================
10:24:54 INFO  Id:    SoftwareManagement.sm_apt_install_remove_default
10:24:54 INFO  Dir:   software_management_end_to_end/
10:24:54 INFO  Title: Validate end to end behaviour for the default plugin for installation and removal of packages
10:24:54 INFO  ==============================================================
10:24:54 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:24:54 INFO  EnvironmentC8y Setup
10:24:54 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:24:55 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
10:24:55 INFO  Delaying execution by 6 seconds
10:25:15 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
10:25:15 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:25:16 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:25:16 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:25:18 INFO  State of current operation: FAILED
10:25:19 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_default/run.py", line 27, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
10:25:19 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
10:25:19 INFO  
10:25:19 INFO  cleanup:
10:25:23 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:25:23 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:25:23 INFO  
10:25:23 INFO  Test duration: 29.70 secs
10:25:23 INFO  Test final outcome:  BLOCKED
10:25:23 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
10:25:23 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_default">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED" />
		<system-out>10:24:52 INFO  ==============================================================
10:24:52 INFO  Id:    SoftwareManagement.sm_apt_install_remove_default
10:24:52 INFO  Dir:   software_management_end_to_end/
10:24:52 INFO  Title: Validate end to end behaviour for the default plugin for installation and removal of packages
10:24:52 INFO  ==============================================================
10:24:52 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:24:52 INFO  EnvironmentC8y Setup
10:24:53 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:24:53 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
10:24:53 INFO  Delaying execution by 6 seconds
10:25:13 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
10:25:14 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:25:14 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:25:15 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:25:17 INFO  State of current operation: FAILED
10:25:17 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_default/run.py", line 27, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
10:25:17 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
10:25:17 INFO  
10:25:17 INFO  cleanup:
10:25:22 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:25:22 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:25:22 INFO  
10:25:22 INFO  Test duration: 30.12 secs
10:25:22 INFO  Test final outcome:  BLOCKED
10:25:22 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
10:25:22 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_default">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED" />
		<system-out>10:24:51 INFO  ==============================================================
10:24:51 INFO  Id:    SoftwareManagement.sm_apt_install_remove_default
10:24:51 INFO  Dir:   software_management_end_to_end/
10:24:51 INFO  Title: Validate end to end behaviour for the default plugin for installation and removal of packages
10:24:51 INFO  ==============================================================
10:24:51 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:24:51 INFO  EnvironmentC8y Setup
10:24:52 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:24:52 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
10:24:52 INFO  Delaying execution by 7 seconds
10:25:12 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
10:25:13 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:25:14 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:25:14 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:25:16 INFO  State of current operation: FAILED
10:25:17 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_default/run.py", line 27, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
10:25:17 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
10:25:17 INFO  
10:25:17 INFO  cleanup:
10:25:20 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:25:21 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:25:21 INFO  
10:25:21 INFO  Test duration: 29.91 secs
10:25:21 INFO  Test final outcome:  BLOCKED
10:25:21 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
10:25:21 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_default" />
</testsuite><testsuite name="SoftwareManagement.sm_apt_install_remove_multiple" tests="4" errors="0" failures="4" skipped="0" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_multiple">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED" />
		<system-out>10:25:23 INFO  ==============================================================
10:25:23 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple
10:25:23 INFO  Dir:   software_management_end_to_end/
10:25:23 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages
10:25:23 INFO  ==============================================================
10:25:23 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:25:23 INFO  EnvironmentC8y Setup
10:25:24 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:25:24 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
10:25:24 INFO  Delaying execution by 6 seconds
10:25:44 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
10:25:45 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:25:45 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:25:46 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:25:48 INFO  State of current operation: FAILED
10:25:48 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/run.py", line 54, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
10:25:48 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
10:25:48 INFO  
10:25:48 INFO  cleanup:
10:25:52 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:25:53 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:25:53 INFO  
10:25:53 INFO  Test duration: 29.36 secs
10:25:53 INFO  Test final outcome:  BLOCKED
10:25:53 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
10:25:53 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_multiple">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED" />
		<system-out>10:25:22 INFO  ==============================================================
10:25:22 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple
10:25:22 INFO  Dir:   software_management_end_to_end/
10:25:22 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages
10:25:22 INFO  ==============================================================
10:25:22 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:25:22 INFO  EnvironmentC8y Setup
10:25:23 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:25:23 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
10:25:23 INFO  Delaying execution by 6 seconds
10:25:44 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
10:25:44 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:25:45 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:25:45 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:25:48 INFO  State of current operation: FAILED
10:25:48 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/run.py", line 54, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
10:25:48 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
10:25:48 INFO  
10:25:48 INFO  cleanup:
10:25:52 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:25:53 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:25:53 INFO  
10:25:53 INFO  Test duration: 30.36 secs
10:25:53 INFO  Test final outcome:  BLOCKED
10:25:53 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
10:25:53 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_multiple">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED" />
		<system-out>10:25:21 INFO  ==============================================================
10:25:21 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple
10:25:21 INFO  Dir:   software_management_end_to_end/
10:25:21 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages
10:25:21 INFO  ==============================================================
10:25:21 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:25:21 INFO  EnvironmentC8y Setup
10:25:22 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:25:22 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
10:25:22 INFO  Delaying execution by 7 seconds
10:25:43 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
10:25:43 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:25:44 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:25:44 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:25:47 INFO  State of current operation: FAILED
10:25:47 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple/run.py", line 54, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
10:25:47 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
10:25:47 INFO  
10:25:47 INFO  cleanup:
10:25:51 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:25:51 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:25:51 INFO  
10:25:51 INFO  Test duration: 30.29 secs
10:25:51 INFO  Test final outcome:  BLOCKED
10:25:51 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
10:25:51 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_multiple">
		<failure message="FAILED: Assert that (False == value) with value=True" type="FAILED" />
		<system-out>10:52:03 INFO  ==============================================================
10:52:03 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple
10:52:03 INFO  Dir:   software_management_end_to_end/
10:52:03 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages
10:52:03 INFO  ==============================================================
10:52:03 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:52:03 INFO  EnvironmentC8y Setup
10:52:04 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:52:04 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
10:52:04 INFO  Delaying execution by 7 seconds
10:52:25 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
10:52:26 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:52:26 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:52:27 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:52:29 INFO  State of current operation: SUCCESSFUL
10:52:29 INFO  Assert that (False == value) with value=False ... passed
10:52:30 INFO  Assert that (False == value) with value=False ... passed
10:52:30 INFO  Assert that (False == value) with value=False ... passed
10:52:30 INFO  Package robotfindskitten is installed
10:52:30 WARN  Assert that (False == value) with value=True ... failed 
10:52:30 INFO  Response status: 201
10:52:30 INFO  Response to action: {
    "creationTime": "2022-04-14T10:52:30.801Z",
    "deviceName": "mythicd",
    "deviceId": "17331100",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17330354",
    "id": "17330354",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5474869', 'name': 'robotfindskitten', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5475279', 'name': 'squirrel3', 'url': ' ', 'version': '::apt'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "asciijump",
            "action": "install",
            "id": "5475369",
            "version": "::apt",
            "url": " "
        },
        {
            "name": "robotfindskitten",
            "action": "install",
            "id": "5474869",
            "version": "::apt",
            "url": " "
        },
        {
            "name": "squirrel3",
            "action": "install",
            "id": "5475279",
            "version": "::apt",
            "url": " "
        }
    ]
}
10:52:30 INFO  Started operation: {'creationTime': '2022-04-14T10:52:30.801Z', 'deviceName': 'mythicd', 'deviceId': '17331100', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17330354', 'id': '17330354', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5474869', 'name': 'robotfindskitten', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5475279', 'name': 'squirrel3', 'url': ' ', 'version': '::apt'}]", 'c8y_SoftwareUpdate': [{'name': 'asciijump', 'action': 'install', 'id': '5475369', 'version': '::apt', 'url': ' '}, {'name': 'robotfindskitten', 'action': 'install', 'id': '5474869', 'version': '::apt', 'url': ' '}, {'name': 'squirrel3', 'action': 'install', 'id': '5475279', 'version': '::apt', 'url': ' '}]}
10:52:33 INFO  State of operation 17330354 : PENDING
10:52:35 INFO  State of operation 17330354 : EXECUTING
10:52:37 INFO  State of operation 17330354 : EXECUTING
10:52:39 INFO  State of operation 17330354 : EXECUTING
10:52:41 INFO  State of operation 17330354 : EXECUTING
10:52:44 INFO  State of operation 17330354 : EXECUTING
10:52:46 INFO  State of operation 17330354 : EXECUTING
10:52:49 INFO  State of operation 17330354 : EXECUTING
10:52:52 INFO  State of operation 17330354 : EXECUTING
10:52:54 INFO  State of operation 17330354 : EXECUTING
10:52:56 INFO  State of operation 17330354 : EXECUTING
10:52:59 INFO  State of operation 17330354 : EXECUTING
10:53:01 INFO  State of operation 17330354 : EXECUTING
10:53:03 INFO  State of operation 17330354 : EXECUTING
10:53:05 INFO  State of operation 17330354 : EXECUTING
10:53:08 INFO  State of operation 17330354 : EXECUTING
10:53:10 INFO  State of operation 17330354 : EXECUTING
10:53:12 INFO  State of operation 17330354 : EXECUTING
10:53:15 INFO  State of operation 17330354 : EXECUTING
10:53:17 INFO  State of operation 17330354 : EXECUTING
10:53:20 INFO  State of operation 17330354 : EXECUTING
10:53:22 INFO  State of operation 17330354 : EXECUTING
10:53:24 INFO  State of operation 17330354 : EXECUTING
10:53:26 INFO  State of operation 17330354 : EXECUTING
10:53:29 INFO  State of operation 17330354 : EXECUTING
10:53:31 INFO  State of operation 17330354 : EXECUTING
10:53:34 INFO  State of operation 17330354 : EXECUTING
10:53:36 INFO  State of operation 17330354 : EXECUTING
10:53:39 INFO  State of operation 17330354 : EXECUTING
10:53:41 INFO  State of operation 17330354 : EXECUTING
10:53:44 INFO  State of operation 17330354 : EXECUTING
10:53:46 INFO  State of operation 17330354 : EXECUTING
10:53:48 INFO  State of operation 17330354 : EXECUTING
10:53:50 INFO  State of operation 17330354 : EXECUTING
10:53:52 INFO  State of operation 17330354 : SUCCESSFUL
10:53:53 INFO  Assert that (False == value) with value=False ... passed
10:53:53 INFO  Package asciijump is installed
10:53:53 INFO  Assert that (True == value) with value=True ... passed
10:53:53 INFO  Package squirrel3 is installed
10:53:53 INFO  Assert that (True == value) with value=True ... passed
10:53:53 INFO  Package robotfindskitten is installed
10:53:53 INFO  Assert that (True == value) with value=True ... passed
10:53:54 INFO  Response status: 201
10:53:54 INFO  Response to action: {
    "creationTime": "2022-04-14T10:53:54.111Z",
    "deviceName": "mythicd",
    "deviceId": "17331100",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17330356",
    "id": "17330356",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'action': 'delete', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'delete', 'id': '5474869', 'name': 'robotfindskitten', 'url': ' ', 'version': '::apt'}, {'action': 'delete', 'id': '5475279', 'name': 'squirrel3', 'url': ' ', 'version': '::apt'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "asciijump",
            "action": "delete",
            "id": "5475369",
            "version": "::apt",
            "url": " "
        },
        {
            "name": "robotfindskitten",
            "action": "delete",
            "id": "5474869",
            "version": "::apt",
            "url": " "
        },
        {
            "name": "squirrel3",
            "action": "delete",
            "id": "5475279",
            "version": "::apt",
            "url": " "
        }
    ]
}
10:53:54 INFO  Started operation: {'creationTime': '2022-04-14T10:53:54.111Z', 'deviceName': 'mythicd', 'deviceId': '17331100', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17330356', 'id': '17330356', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'action': 'delete', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'delete', 'id': '5474869', 'name': 'robotfindskitten', 'url': ' ', 'version': '::apt'}, {'action': 'delete', 'id': '5475279', 'name': 'squirrel3', 'url': ' ', 'version': '::apt'}]", 'c8y_SoftwareUpdate': [{'name': 'asciijump', 'action': 'delete', 'id': '5475369', 'version': '::apt', 'url': ' '}, {'name': 'robotfindskitten', 'action': 'delete', 'id': '5474869', 'version': '::apt', 'url': ' '}, {'name': 'squirrel3', 'action': 'delete', 'id': '5475279', 'version': '::apt', 'url': ' '}]}
10:53:56 INFO  State of operation 17330356 : PENDING
10:53:58 INFO  State of operation 17330356 : EXECUTING
10:54:00 INFO  State of operation 17330356 : EXECUTING
10:54:03 INFO  State of operation 17330356 : EXECUTING
10:54:05 INFO  State of operation 17330356 : EXECUTING
10:54:07 INFO  State of operation 17330356 : EXECUTING
10:54:10 INFO  State of operation 17330356 : EXECUTING
10:54:13 INFO  State of operation 17330356 : EXECUTING
10:54:15 INFO  State of operation 17330356 : EXECUTING
10:54:18 INFO  State of operation 17330356 : EXECUTING
10:54:20 INFO  State of operation 17330356 : EXECUTING
10:54:22 INFO  State of operation 17330356 : EXECUTING
10:54:24 INFO  State of operation 17330356 : EXECUTING
10:54:27 INFO  State of operation 17330356 : EXECUTING
10:54:29 INFO  State of operation 17330356 : EXECUTING
10:54:31 INFO  State of operation 17330356 : EXECUTING
10:54:34 INFO  State of operation 17330356 : EXECUTING
10:54:36 INFO  State of operation 17330356 : EXECUTING
10:54:39 INFO  State of operation 17330356 : EXECUTING
10:54:41 INFO  State of operation 17330356 : EXECUTING
10:54:43 INFO  State of operation 17330356 : EXECUTING
10:54:46 INFO  State of operation 17330356 : EXECUTING
10:54:48 INFO  State of operation 17330356 : EXECUTING
10:54:50 INFO  State of operation 17330356 : EXECUTING
10:54:53 INFO  State of operation 17330356 : EXECUTING
10:54:55 INFO  State of operation 17330356 : EXECUTING
10:54:58 INFO  State of operation 17330356 : EXECUTING
10:55:00 INFO  State of operation 17330356 : EXECUTING
10:55:02 INFO  State of operation 17330356 : SUCCESSFUL
10:55:03 INFO  Assert that (False == value) with value=False ... passed
10:55:03 INFO  Assert that (False == value) with value=False ... passed
10:55:03 INFO  Assert that (False == value) with value=False ... passed
10:55:03 INFO  Assert that (False == value) with value=False ... passed
10:55:03 INFO  
10:55:03 INFO  cleanup:
10:55:07 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:55:08 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:55:08 INFO  
10:55:08 INFO  Test duration: 184.51 secs
10:55:08 INFO  Test final outcome:  FAILED
10:55:08 INFO  Test outcome reason: Assert that (False == value) with value=True
10:55:08 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_apt_install_remove_multiple_mixed" tests="4" errors="0" failures="4" skipped="0" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_multiple_mixed">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED" />
		<system-out>10:25:53 INFO  ==============================================================
10:25:53 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple_mixed
10:25:53 INFO  Dir:   software_management_end_to_end/
10:25:53 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages with mixed versions
10:25:53 INFO  ==============================================================
10:25:53 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:25:53 INFO  EnvironmentC8y Setup
10:25:53 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:25:54 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
10:25:54 INFO  Delaying execution by 6 seconds
10:26:14 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
10:26:14 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:26:15 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:26:15 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:26:18 INFO  State of current operation: FAILED
10:26:18 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple_mixed/run.py", line 75, in setup
    self.assertThat("False == value", value=self.check_is_installed("asciijump"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
10:26:18 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
10:26:18 INFO  
10:26:18 INFO  cleanup:
10:26:22 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:26:23 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:26:23 INFO  
10:26:23 INFO  Test duration: 29.69 secs
10:26:23 INFO  Test final outcome:  BLOCKED
10:26:23 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
10:26:23 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_multiple_mixed">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED" />
		<system-out>10:25:53 INFO  ==============================================================
10:25:53 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple_mixed
10:25:53 INFO  Dir:   software_management_end_to_end/
10:25:53 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages with mixed versions
10:25:53 INFO  ==============================================================
10:25:53 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:25:53 INFO  EnvironmentC8y Setup
10:25:53 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:25:53 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
10:25:53 INFO  Delaying execution by 7 seconds
10:26:15 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
10:26:15 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:26:16 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:26:16 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:26:19 INFO  State of current operation: FAILED
10:26:19 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple_mixed/run.py", line 75, in setup
    self.assertThat("False == value", value=self.check_is_installed("asciijump"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
10:26:19 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
10:26:19 INFO  
10:26:19 INFO  cleanup:
10:26:23 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:26:24 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:26:24 INFO  
10:26:24 INFO  Test duration: 30.97 secs
10:26:24 INFO  Test final outcome:  BLOCKED
10:26:24 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
10:26:24 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_multiple_mixed">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED" />
		<system-out>10:25:51 INFO  ==============================================================
10:25:51 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple_mixed
10:25:51 INFO  Dir:   software_management_end_to_end/
10:25:51 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages with mixed versions
10:25:51 INFO  ==============================================================
10:25:51 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:25:51 INFO  EnvironmentC8y Setup
10:25:52 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:25:52 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
10:25:52 INFO  Delaying execution by 7 seconds
10:26:13 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
10:26:14 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:26:14 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:26:15 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:26:17 INFO  State of current operation: FAILED
10:26:17 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple_mixed/run.py", line 75, in setup
    self.assertThat("False == value", value=self.check_is_installed("asciijump"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
10:26:17 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
10:26:17 INFO  
10:26:17 INFO  cleanup:
10:26:21 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:26:22 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:26:22 INFO  
10:26:22 INFO  Test duration: 30.35 secs
10:26:22 INFO  Test final outcome:  BLOCKED
10:26:22 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
10:26:22 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_multiple_mixed">
		<failure message="BLOCKED: SystemError: Timeout while waiting for status SUCCESSFUL or False" type="BLOCKED" />
		<system-out>10:55:08 INFO  ==============================================================
10:55:08 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple_mixed
10:55:08 INFO  Dir:   software_management_end_to_end/
10:55:08 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages with mixed versions
10:55:08 INFO  ==============================================================
10:55:08 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:55:08 INFO  EnvironmentC8y Setup
10:55:09 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:55:09 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
10:55:09 INFO  Delaying execution by 6 seconds
10:55:29 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
10:55:29 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:55:30 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:55:30 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:55:33 INFO  State of current operation: SUCCESSFUL
10:55:33 INFO  Assert that (False == value) with value=False ... passed
10:55:33 INFO  Assert that (False == value) with value=False ... passed
10:55:33 INFO  Assert that (False == value) with value=False ... passed
10:55:34 INFO  Assert that (False == value) with value=False ... passed
10:55:34 INFO  Assert that (False == value) with value=False ... passed
10:55:35 INFO  Response status: 201
10:55:35 INFO  Response to action: {
    "delivery": {
        "time": "2022-04-14T10:55:35.753Z",
        "log": [],
        "status": "PENDING"
    },
    "creationTime": "2022-04-14T10:55:35.736Z",
    "deviceName": "mythicd",
    "deviceId": "17331100",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17330358",
    "id": "17330358",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5474869', 'name': 'robotfindskitten', 'url': ' ', 'version': ' '}, {'action': 'install', 'id': '5475279', 'name': 'squirrel3', 'url': ' ', 'version': '3.1-7::apt'}, {'action': 'install', 'id': '5152439', 'name': 'rolldice', 'url': ' ', 'version': '1.16-1+b1'}, {'action': 'install', 'id': '5439204', 'name': 'moon-buggy', 'url': ' ', 'version': '1:1.0.51-12'}, {'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "asciijump",
            "action": "install",
            "id": "5475369",
            "version": "::apt",
            "url": " "
        },
        {
            "name": "robotfindskitten",
            "action": "install",
            "id": "5474869",
            "version": " ",
            "url": " "
        },
        {
            "name": "squirrel3",
            "action": "install",
            "id": "5475279",
            "version": "3.1-7::apt",
            "url": " "
        },
        {
            "name": "rolldice",
            "action": "install",
            "id": "5152439",
            "version": "1.16-1+b1",
            "url": " "
        },
        {
            "name": "moon-buggy",
            "action": "install",
            "id": "5439204",
            "version": "1:1.0.51-12",
            "url": " "
        },
        {
            "name": "asciijump",
            "action": "install",
            "id": "5475369",
            "version": "::apt",
            "url": " "
        }
    ]
}
10:55:35 INFO  Started operation: {'delivery': {'time': '2022-04-14T10:55:35.753Z', 'log': [], 'status': 'PENDING'}, 'creationTime': '2022-04-14T10:55:35.736Z', 'deviceName': 'mythicd', 'deviceId': '17331100', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17330358', 'id': '17330358', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5474869', 'name': 'robotfindskitten', 'url': ' ', 'version': ' '}, {'action': 'install', 'id': '5475279', 'name': 'squirrel3', 'url': ' ', 'version': '3.1-7::apt'}, {'action': 'install', 'id': '5152439', 'name': 'rolldice', 'url': ' ', 'version': '1.16-1+b1'}, {'action': 'install', 'id': '5439204', 'name': 'moon-buggy', 'url': ' ', 'version': '1:1.0.51-12'}, {'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}]", 'c8y_SoftwareUpdate': [{'name': 'asciijump', 'action': 'install', 'id': '5475369', 'version': '::apt', 'url': ' '}, {'name': 'robotfindskitten', 'action': 'install', 'id': '5474869', 'version': ' ', 'url': ' '}, {'name': 'squirrel3', 'action': 'install', 'id': '5475279', 'version': '3.1-7::apt', 'url': ' '}, {'name': 'rolldice', 'action': 'install', 'id': '5152439', 'version': '1.16-1+b1', 'url': ' '}, {'name': 'moon-buggy', 'action': 'install', 'id': '5439204', 'version': '1:1.0.51-12', 'url': ' '}, {'name': 'asciijump', 'action': 'install', 'id': '5475369', 'version': '::apt', 'url': ' '}]}
10:55:37 INFO  State of operation 17330358 : PENDING
10:55:40 INFO  State of operation 17330358 : EXECUTING
10:55:42 INFO  State of operation 17330358 : EXECUTING
10:55:44 INFO  State of operation 17330358 : EXECUTING
10:55:46 INFO  State of operation 17330358 : EXECUTING
10:55:49 INFO  State of operation 17330358 : EXECUTING
10:55:51 INFO  State of operation 17330358 : EXECUTING
10:55:54 INFO  State of operation 17330358 : EXECUTING
10:55:56 INFO  State of operation 17330358 : EXECUTING
10:55:59 INFO  State of operation 17330358 : EXECUTING
10:56:01 INFO  State of operation 17330358 : EXECUTING
10:56:03 INFO  State of operation 17330358 : EXECUTING
10:56:05 INFO  State of operation 17330358 : EXECUTING
10:56:07 INFO  State of operation 17330358 : EXECUTING
10:56:10 INFO  State of operation 17330358 : EXECUTING
10:56:12 INFO  State of operation 17330358 : EXECUTING
10:56:14 INFO  State of operation 17330358 : EXECUTING
10:56:16 INFO  State of operation 17330358 : EXECUTING
10:56:19 INFO  State of operation 17330358 : EXECUTING
10:56:21 INFO  State of operation 17330358 : EXECUTING
10:56:24 INFO  State of operation 17330358 : EXECUTING
10:56:26 INFO  State of operation 17330358 : EXECUTING
10:56:29 INFO  State of operation 17330358 : EXECUTING
10:56:31 INFO  State of operation 17330358 : EXECUTING
10:56:33 INFO  State of operation 17330358 : EXECUTING
10:56:36 INFO  State of operation 17330358 : EXECUTING
10:56:38 INFO  State of operation 17330358 : EXECUTING
10:56:41 INFO  State of operation 17330358 : EXECUTING
10:56:43 INFO  State of operation 17330358 : EXECUTING
10:56:45 INFO  State of operation 17330358 : EXECUTING
10:56:48 INFO  State of operation 17330358 : EXECUTING
10:56:50 INFO  State of operation 17330358 : EXECUTING
10:56:52 INFO  State of operation 17330358 : EXECUTING
10:56:54 INFO  State of operation 17330358 : EXECUTING
10:56:57 INFO  State of operation 17330358 : EXECUTING
10:56:59 INFO  State of operation 17330358 : EXECUTING
10:57:01 INFO  State of operation 17330358 : EXECUTING
10:57:03 INFO  State of operation 17330358 : EXECUTING
10:57:05 INFO  State of operation 17330358 : EXECUTING
10:57:08 INFO  State of operation 17330358 : EXECUTING
10:57:11 INFO  State of operation 17330358 : EXECUTING
10:57:13 INFO  State of operation 17330358 : EXECUTING
10:57:16 INFO  State of operation 17330358 : EXECUTING
10:57:18 INFO  State of operation 17330358 : EXECUTING
10:57:20 INFO  State of operation 17330358 : EXECUTING
10:57:22 INFO  State of operation 17330358 : EXECUTING
10:57:25 INFO  State of operation 17330358 : EXECUTING
10:57:27 INFO  State of operation 17330358 : EXECUTING
10:57:29 INFO  State of operation 17330358 : EXECUTING
10:57:32 INFO  State of operation 17330358 : EXECUTING
10:57:34 INFO  State of operation 17330358 : EXECUTING
10:57:36 INFO  State of operation 17330358 : EXECUTING
10:57:39 INFO  State of operation 17330358 : EXECUTING
10:57:41 INFO  State of operation 17330358 : EXECUTING
10:57:43 INFO  State of operation 17330358 : EXECUTING
10:57:46 INFO  State of operation 17330358 : EXECUTING
10:57:48 INFO  State of operation 17330358 : EXECUTING
10:57:51 INFO  State of operation 17330358 : EXECUTING
10:57:53 INFO  State of operation 17330358 : EXECUTING
10:57:55 INFO  State of operation 17330358 : EXECUTING
10:57:57 INFO  State of operation 17330358 : EXECUTING
10:57:59 WARN  SystemError occurred while running test - Timeout while waiting for status SUCCESSFUL or False
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1294, in __call__
    self.testObj.execute()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple_mixed/run.py", line 89, in execute
    self.wait_until_succcess()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 324, in wait_until_succcess
    self.wait_until_status("SUCCESSFUL")
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 381, in wait_until_status
    "Timeout while waiting for status %s or %s" % (status, status2)
SystemError: Timeout while waiting for status SUCCESSFUL or False
10:58:00 WARN  SystemError: Timeout while waiting for status SUCCESSFUL or False ... blocked 
10:58:00 INFO  
10:58:00 INFO  cleanup:
10:58:05 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:58:06 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:58:06 INFO  
10:58:06 INFO  Test duration: 177.78 secs
10:58:06 INFO  Test final outcome:  BLOCKED
10:58:06 INFO  Test outcome reason: SystemError: Timeout while waiting for status SUCCESSFUL or False
10:58:06 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_apt_install_remove_with_version" tests="4" errors="0" failures="3" skipped="0" time="0"><testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_with_version">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED" />
		<system-out>10:26:23 INFO  ==============================================================
10:26:23 INFO  Id:    SoftwareManagement.sm_apt_install_remove_with_version
10:26:23 INFO  Dir:   software_management_end_to_end/
10:26:23 INFO  Title: Validate end to end behaviour for the apt plugin for packages with version
10:26:23 INFO  ==============================================================
10:26:23 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:26:23 INFO  EnvironmentC8y Setup
10:26:23 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:26:23 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
10:26:23 INFO  Delaying execution by 6 seconds
10:26:43 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
10:26:44 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:26:44 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:26:45 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:26:47 INFO  State of current operation: FAILED
10:26:47 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_with_version/run.py", line 29, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
10:26:47 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
10:26:47 INFO  
10:26:47 INFO  cleanup:
10:26:51 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:26:52 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:26:52 INFO  
10:26:52 INFO  Test duration: 29.23 secs
10:26:52 INFO  Test final outcome:  BLOCKED
10:26:52 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
10:26:52 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_with_version">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED" />
		<system-out>10:26:24 INFO  ==============================================================
10:26:24 INFO  Id:    SoftwareManagement.sm_apt_install_remove_with_version
10:26:24 INFO  Dir:   software_management_end_to_end/
10:26:24 INFO  Title: Validate end to end behaviour for the apt plugin for packages with version
10:26:24 INFO  ==============================================================
10:26:24 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:26:24 INFO  EnvironmentC8y Setup
10:26:24 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:26:24 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
10:26:24 INFO  Delaying execution by 6 seconds
10:26:45 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
10:26:46 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:26:46 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:26:47 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:26:49 INFO  State of current operation: FAILED
10:26:49 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_with_version/run.py", line 29, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
10:26:49 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
10:26:49 INFO  
10:26:49 INFO  cleanup:
10:26:54 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:26:54 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:26:54 INFO  
10:26:54 INFO  Test duration: 30.37 secs
10:26:54 INFO  Test final outcome:  BLOCKED
10:26:54 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
10:26:54 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_with_version">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not iterable" type="BLOCKED" />
		<system-out>10:26:22 INFO  ==============================================================
10:26:22 INFO  Id:    SoftwareManagement.sm_apt_install_remove_with_version
10:26:22 INFO  Dir:   software_management_end_to_end/
10:26:22 INFO  Title: Validate end to end behaviour for the apt plugin for packages with version
10:26:22 INFO  ==============================================================
10:26:22 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:26:22 INFO  EnvironmentC8y Setup
10:26:22 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:26:23 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
10:26:23 INFO  Delaying execution by 6 seconds
10:26:42 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
10:26:43 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:26:43 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:26:44 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:26:46 INFO  State of current operation: FAILED
10:26:46 WARN  TypeError occurred while running test - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_with_version/run.py", line 29, in setup
    self.assertThat("False == value", value=self.check_is_installed("rolldice"))
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 398, in check_is_installed
    for package in package_list:
TypeError: 'NoneType' object is not iterable
10:26:46 WARN  TypeError: 'NoneType' object is not iterable ... blocked 
10:26:46 INFO  
10:26:46 INFO  cleanup:
10:26:50 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:26:51 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:26:51 INFO  
10:26:51 INFO  Test duration: 28.93 secs
10:26:51 INFO  Test final outcome:  BLOCKED
10:26:51 INFO  Test outcome reason: TypeError: 'NoneType' object is not iterable
10:26:51 INFO  
</system-out>
	</testcase>
<testcase classname="PySysTest" name="SoftwareManagement.sm_apt_install_remove_with_version" />
</testsuite><testsuite name="apt_fail_noarg" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginFailNoArg" name="apt_fail_noarg" />
<testcase classname="AptPluginFailNoArg" name="apt_fail_noarg" />
<testcase classname="AptPluginFailNoArg" name="apt_fail_noarg" />
<testcase classname="AptPluginFailNoArg" name="apt_fail_noarg" />
</testsuite><testsuite name="apt_finalize" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginFinalize" name="apt_finalize" />
<testcase classname="AptPluginFinalize" name="apt_finalize" />
<testcase classname="AptPluginFinalize" name="apt_finalize" />
<testcase classname="AptPluginFinalize" name="apt_finalize" />
</testsuite><testsuite name="apt_install" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginInstallDense" name="apt_install" />
<testcase classname="AptPluginInstallDense" name="apt_install" />
<testcase classname="AptPluginInstallDense" name="apt_install" />
<testcase classname="AptPluginInstallDense" name="apt_install" />
</testsuite><testsuite name="apt_install_fail" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginInstallFail" name="apt_install_fail" />
<testcase classname="AptPluginInstallFail" name="apt_install_fail" />
<testcase classname="AptPluginInstallFail" name="apt_install_fail" />
<testcase classname="AptPluginInstallFail" name="apt_install_fail" />
</testsuite><testsuite name="apt_install_local_file" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginInstallFromLocalFile" name="apt_install_local_file" />
<testcase classname="AptPluginInstallFromLocalFile" name="apt_install_local_file" />
<testcase classname="AptPluginInstallFromLocalFile" name="apt_install_local_file" />
<testcase classname="AptPluginInstallFromLocalFile" name="apt_install_local_file" />
</testsuite><testsuite name="apt_install_local_file_fail" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginInstallFromLocalFileFail" name="apt_install_local_file_fail" />
<testcase classname="AptPluginInstallFromLocalFileFail" name="apt_install_local_file_fail" />
<testcase classname="AptPluginInstallFromLocalFileFail" name="apt_install_local_file_fail" />
<testcase classname="AptPluginInstallFromLocalFileFail" name="apt_install_local_file_fail" />
</testsuite><testsuite name="apt_install_local_file_with_version" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginInstallFromLocalFileWithVersion" name="apt_install_local_file_with_version" />
<testcase classname="AptPluginInstallFromLocalFileWithVersion" name="apt_install_local_file_with_version" />
<testcase classname="AptPluginInstallFromLocalFileWithVersion" name="apt_install_local_file_with_version" />
<testcase classname="AptPluginInstallFromLocalFileWithVersion" name="apt_install_local_file_with_version" />
</testsuite><testsuite name="apt_install_local_file_with_version_fail" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginInstallFromLocalFileWithVersionFail" name="apt_install_local_file_with_version_fail" />
<testcase classname="AptPluginInstallFromLocalFileWithVersionFail" name="apt_install_local_file_with_version_fail" />
<testcase classname="AptPluginInstallFromLocalFileWithVersionFail" name="apt_install_local_file_with_version_fail" />
<testcase classname="AptPluginInstallFromLocalFileWithVersionFail" name="apt_install_local_file_with_version_fail" />
</testsuite><testsuite name="apt_list_format" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginListFormat" name="apt_list_format" />
<testcase classname="AptPluginListFormat" name="apt_list_format" />
<testcase classname="AptPluginListFormat" name="apt_list_format" />
<testcase classname="AptPluginListFormat" name="apt_list_format" />
</testsuite><testsuite name="apt_prepare" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginPrepare" name="apt_prepare" />
<testcase classname="AptPluginPrepare" name="apt_prepare" />
<testcase classname="AptPluginPrepare" name="apt_prepare" />
<testcase classname="AptPluginPrepare" name="apt_prepare" />
</testsuite><testsuite name="apt_prepare_install_finalize" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginPrepareInstallFinalize" name="apt_prepare_install_finalize" />
<testcase classname="AptPluginPrepareInstallFinalize" name="apt_prepare_install_finalize" />
<testcase classname="AptPluginPrepareInstallFinalize" name="apt_prepare_install_finalize" />
<testcase classname="AptPluginPrepareInstallFinalize" name="apt_prepare_install_finalize" />
</testsuite><testsuite name="apt_remove" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginRemoveDense" name="apt_remove" />
<testcase classname="AptPluginRemoveDense" name="apt_remove" />
<testcase classname="AptPluginRemoveDense" name="apt_remove" />
<testcase classname="AptPluginRemoveDense" name="apt_remove" />
</testsuite><testsuite name="apt_remove_fail" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginRemoveFails" name="apt_remove_fail" />
<testcase classname="AptPluginRemoveFails" name="apt_remove_fail" />
<testcase classname="AptPluginRemoveFails" name="apt_remove_fail" />
<testcase classname="AptPluginRemoveFails" name="apt_remove_fail" />
</testsuite><testsuite name="apt_sequence_install_with_version" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginPrepInstallWithVersionFinalize" name="apt_sequence_install_with_version" />
<testcase classname="AptPluginPrepInstallWithVersionFinalize" name="apt_sequence_install_with_version" />
<testcase classname="AptPluginPrepInstallWithVersionFinalize" name="apt_sequence_install_with_version" />
<testcase classname="AptPluginPrepInstallWithVersionFinalize" name="apt_sequence_install_with_version" />
</testsuite><testsuite name="apt_sequence_install_with_version_fail" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginInstallWithVersionFails" name="apt_sequence_install_with_version_fail" />
<testcase classname="AptPluginInstallWithVersionFails" name="apt_sequence_install_with_version_fail" />
<testcase classname="AptPluginInstallWithVersionFails" name="apt_sequence_install_with_version_fail" />
<testcase classname="AptPluginInstallWithVersionFails" name="apt_sequence_install_with_version_fail" />
</testsuite><testsuite name="apt_sequence_remove" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginInstallPrepareRemoveFinalize" name="apt_sequence_remove" />
<testcase classname="AptPluginInstallPrepareRemoveFinalize" name="apt_sequence_remove" />
<testcase classname="AptPluginInstallPrepareRemoveFinalize" name="apt_sequence_remove" />
<testcase classname="AptPluginInstallPrepareRemoveFinalize" name="apt_sequence_remove" />
</testsuite><testsuite name="apt_sequence_remove_with_version" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginRemoveWithVersion" name="apt_sequence_remove_with_version" />
<testcase classname="AptPluginRemoveWithVersion" name="apt_sequence_remove_with_version" />
<testcase classname="AptPluginRemoveWithVersion" name="apt_sequence_remove_with_version" />
<testcase classname="AptPluginRemoveWithVersion" name="apt_sequence_remove_with_version" />
</testsuite><testsuite name="apt_sequence_remove_with_version_fail" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginRemoveWithVersionFails" name="apt_sequence_remove_with_version_fail" />
<testcase classname="AptPluginRemoveWithVersionFails" name="apt_sequence_remove_with_version_fail" />
<testcase classname="AptPluginRemoveWithVersionFails" name="apt_sequence_remove_with_version_fail" />
<testcase classname="AptPluginRemoveWithVersionFails" name="apt_sequence_remove_with_version_fail" />
</testsuite><testsuite name="apt_update_list" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginUpdateList" name="apt_update_list" />
<testcase classname="AptPluginUpdateList" name="apt_update_list" />
<testcase classname="AptPluginUpdateList" name="apt_update_list" />
<testcase classname="AptPluginUpdateList" name="apt_update_list" />
</testsuite><testsuite name="apt_wrong_option" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="AptPluginWrongOption" name="apt_wrong_option" />
<testcase classname="AptPluginWrongOption" name="apt_wrong_option" />
<testcase classname="AptPluginWrongOption" name="apt_wrong_option" />
<testcase classname="AptPluginWrongOption" name="apt_wrong_option" />
</testsuite><testsuite name="SoftwareManagement.Plugin.apama_plugin_install" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="ApamaPluginInstallTest" name="SoftwareManagement.Plugin.apama_plugin_install" />
<testcase classname="ApamaPluginInstallTest" name="SoftwareManagement.Plugin.apama_plugin_install" />
<testcase classname="ApamaPluginInstallTest" name="SoftwareManagement.Plugin.apama_plugin_install" />
<testcase classname="ApamaPluginInstallTest" name="SoftwareManagement.Plugin.apama_plugin_install" />
</testsuite><testsuite name="SoftwareManagement.Plugin.apama_plugin_mon_support" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="ApamaPluginMonSupportTest" name="SoftwareManagement.Plugin.apama_plugin_mon_support" />
<testcase classname="ApamaPluginMonSupportTest" name="SoftwareManagement.Plugin.apama_plugin_mon_support" />
<testcase classname="ApamaPluginMonSupportTest" name="SoftwareManagement.Plugin.apama_plugin_mon_support" />
<testcase classname="ApamaPluginMonSupportTest" name="SoftwareManagement.Plugin.apama_plugin_mon_support" />
</testsuite><testsuite name="SoftwareManagement.Plugin.apama_plugin_remove" tests="4" errors="0" failures="0" skipped="0" time="0"><testcase classname="ApamaPluginRemoveTest" name="SoftwareManagement.Plugin.apama_plugin_remove" />
<testcase classname="ApamaPluginRemoveTest" name="SoftwareManagement.Plugin.apama_plugin_remove" />
<testcase classname="ApamaPluginRemoveTest" name="SoftwareManagement.Plugin.apama_plugin_remove" />
<testcase classname="ApamaPluginRemoveTest" name="SoftwareManagement.Plugin.apama_plugin_remove" />
</testsuite><testsuite name="SoftwareManagement.Plugin.apama_plugin_update" tests="4" errors="0" failures="4" skipped="0" time="0"><testcase classname="ApamaPluginUpdateTest" name="SoftwareManagement.Plugin.apama_plugin_update">
		<failure message="BLOCKED: sudo&lt;plugin_install&gt; returned non-zero exit code 2" type="BLOCKED" />
		<system-out>10:28:11 INFO  ==============================================================
10:28:11 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_update
10:28:11 INFO  Dir:   plugin_apama/
10:28:11 INFO  Title: Validate apama plugin updating one project with another
10:28:11 INFO  ==============================================================
10:28:11 INFO  Assertion that path exists=False for "/etc/tedge/apama/project" ... passed
10:28:11 INFO  Executed sudo&lt;create_project_dir&gt;, exit status 0
10:28:12 INFO  Executed sudo&lt;unzip_apama_project&gt;, exit status 0
10:28:13 INFO  Executed sudo&lt;move_apama_project&gt;, exit status 0
10:28:13 INFO  Executed sudo&lt;restart_apama_service&gt;, exit status 0
10:28:14 INFO  Executed sudo&lt;apama_correlator_wait&gt;, exit status 0
10:28:14 INFO  Assertion that path exists=True for "/etc/tedge/apama/project" ... passed
10:28:15 INFO  Executed sudo&lt;apama_list_monitors&gt;, exit status 0
10:28:15 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/apama_plugin_update/Output/linux/apama_list_monitors.out ... passed
10:28:16 WARN  Executed sudo&lt;plugin_install&gt;, exit status 2
10:28:16 INFO  Contents of plugin_install.err: 
  ERROR: Directory not empty (os error 39)
  -----

10:28:16 WARN  sudo&lt;plugin_install&gt; returned non-zero exit code 2 ... blocked [run.py:35]
10:28:16 WARN  Aborted test due to BLOCKED outcome
10:28:16 INFO  
10:28:16 INFO  cleanup:
10:28:16 INFO  Removing apama project
10:28:32 INFO  Executed sudo&lt;stop_apama_service&gt;, exit status 0, duration 15 secs
10:28:32 INFO  Executed sudo&lt;remove_apama_project&gt;, exit status 0
10:28:33 INFO  Executed sudo&lt;remove_apama_tmp_dir&gt;, exit status 0
10:28:33 INFO  
10:28:33 INFO  Test duration: 22.03 secs
10:28:33 INFO  Test final outcome:  BLOCKED
10:28:33 INFO  Test outcome reason: sudo&lt;plugin_install&gt; returned non-zero exit code 2
10:28:33 INFO  
</system-out>
	</testcase>
<testcase classname="ApamaPluginUpdateTest" name="SoftwareManagement.Plugin.apama_plugin_update">
		<failure message="BLOCKED: sudo&lt;plugin_install&gt; returned non-zero exit code 2" type="BLOCKED" />
		<system-out>10:28:08 INFO  ==============================================================
10:28:08 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_update
10:28:08 INFO  Dir:   plugin_apama/
10:28:08 INFO  Title: Validate apama plugin updating one project with another
10:28:08 INFO  ==============================================================
10:28:08 INFO  Assertion that path exists=False for "/etc/tedge/apama/project" ... passed
10:28:09 INFO  Executed sudo&lt;create_project_dir&gt;, exit status 0
10:28:10 INFO  Executed sudo&lt;unzip_apama_project&gt;, exit status 0
10:28:10 INFO  Executed sudo&lt;move_apama_project&gt;, exit status 0
10:28:11 INFO  Executed sudo&lt;restart_apama_service&gt;, exit status 0
10:28:12 INFO  Executed sudo&lt;apama_correlator_wait&gt;, exit status 0
10:28:12 INFO  Assertion that path exists=True for "/etc/tedge/apama/project" ... passed
10:28:13 INFO  Executed sudo&lt;apama_list_monitors&gt;, exit status 0
10:28:13 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/apama_plugin_update/Output/linux/apama_list_monitors.out ... passed
10:28:13 WARN  Executed sudo&lt;plugin_install&gt;, exit status 2
10:28:13 INFO  Contents of plugin_install.err: 
  ERROR: Directory not empty (os error 39)
  -----

10:28:14 WARN  sudo&lt;plugin_install&gt; returned non-zero exit code 2 ... blocked [run.py:35]
10:28:14 WARN  Aborted test due to BLOCKED outcome
10:28:14 INFO  
10:28:14 INFO  cleanup:
10:28:14 INFO  Removing apama project
10:28:30 INFO  Executed sudo&lt;stop_apama_service&gt;, exit status 0, duration 16 secs
10:28:30 INFO  Executed sudo&lt;remove_apama_project&gt;, exit status 0
10:28:31 INFO  Executed sudo&lt;remove_apama_tmp_dir&gt;, exit status 0
10:28:31 INFO  
10:28:31 INFO  Test duration: 22.50 secs
10:28:31 INFO  Test final outcome:  BLOCKED
10:28:31 INFO  Test outcome reason: sudo&lt;plugin_install&gt; returned non-zero exit code 2
10:28:31 INFO  
</system-out>
	</testcase>
<testcase classname="ApamaPluginUpdateTest" name="SoftwareManagement.Plugin.apama_plugin_update">
		<failure message="BLOCKED: sudo&lt;plugin_install&gt; returned non-zero exit code 2" type="BLOCKED" />
		<system-out>10:28:10 INFO  ==============================================================
10:28:10 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_update
10:28:10 INFO  Dir:   plugin_apama/
10:28:10 INFO  Title: Validate apama plugin updating one project with another
10:28:10 INFO  ==============================================================
10:28:10 INFO  Assertion that path exists=False for "/etc/tedge/apama/project" ... passed
10:28:10 INFO  Executed sudo&lt;create_project_dir&gt;, exit status 0
10:28:11 INFO  Executed sudo&lt;unzip_apama_project&gt;, exit status 0
10:28:11 INFO  Executed sudo&lt;move_apama_project&gt;, exit status 0
10:28:12 INFO  Executed sudo&lt;restart_apama_service&gt;, exit status 0
10:28:13 INFO  Executed sudo&lt;apama_correlator_wait&gt;, exit status 0
10:28:13 INFO  Assertion that path exists=True for "/etc/tedge/apama/project" ... passed
10:28:14 INFO  Executed sudo&lt;apama_list_monitors&gt;, exit status 0
10:28:14 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/apama_plugin_update/Output/linux/apama_list_monitors.out ... passed
10:28:15 WARN  Executed sudo&lt;plugin_install&gt;, exit status 2
10:28:15 INFO  Contents of plugin_install.err: 
  ERROR: Directory not empty (os error 39)
  -----

10:28:15 WARN  sudo&lt;plugin_install&gt; returned non-zero exit code 2 ... blocked [run.py:35]
10:28:15 WARN  Aborted test due to BLOCKED outcome
10:28:15 INFO  
10:28:15 INFO  cleanup:
10:28:15 INFO  Removing apama project
10:28:31 INFO  Executed sudo&lt;stop_apama_service&gt;, exit status 0, duration 15 secs
10:28:31 INFO  Executed sudo&lt;remove_apama_project&gt;, exit status 0
10:28:32 INFO  Executed sudo&lt;remove_apama_tmp_dir&gt;, exit status 0
10:28:32 INFO  
10:28:32 INFO  Test duration: 21.95 secs
10:28:32 INFO  Test final outcome:  BLOCKED
10:28:32 INFO  Test outcome reason: sudo&lt;plugin_install&gt; returned non-zero exit code 2
10:28:32 INFO  
</system-out>
	</testcase>
<testcase classname="ApamaPluginUpdateTest" name="SoftwareManagement.Plugin.apama_plugin_update">
		<failure message="BLOCKED: sudo&lt;plugin_install&gt; returned non-zero exit code 2" type="BLOCKED" />
		<system-out>11:02:00 INFO  ==============================================================
11:02:00 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_update
11:02:00 INFO  Dir:   plugin_apama/
11:02:00 INFO  Title: Validate apama plugin updating one project with another
11:02:00 INFO  ==============================================================
11:02:00 INFO  Assertion that path exists=False for "/etc/tedge/apama/project" ... passed
11:02:01 INFO  Executed sudo&lt;create_project_dir&gt;, exit status 0
11:02:01 INFO  Executed sudo&lt;unzip_apama_project&gt;, exit status 0
11:02:02 INFO  Executed sudo&lt;move_apama_project&gt;, exit status 0
11:02:03 INFO  Executed sudo&lt;restart_apama_service&gt;, exit status 0
11:02:04 INFO  Executed sudo&lt;apama_correlator_wait&gt;, exit status 0
11:02:04 INFO  Assertion that path exists=True for "/etc/tedge/apama/project" ... passed
11:02:04 INFO  Executed sudo&lt;apama_list_monitors&gt;, exit status 0
11:02:04 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/apama_plugin_update/Output/linux/apama_list_monitors.out ... passed
11:02:05 WARN  Executed sudo&lt;plugin_install&gt;, exit status 2
11:02:05 INFO  Contents of plugin_install.err: 
  ERROR: Directory not empty (os error 39)
  -----

11:02:05 WARN  sudo&lt;plugin_install&gt; returned non-zero exit code 2 ... blocked [run.py:35]
11:02:05 WARN  Aborted test due to BLOCKED outcome
11:02:05 INFO  
11:02:05 INFO  cleanup:
11:02:05 INFO  Removing apama project
11:02:20 INFO  Executed sudo&lt;stop_apama_service&gt;, exit status 0, duration 15 secs
11:02:21 INFO  Executed sudo&lt;remove_apama_project&gt;, exit status 0
11:02:21 INFO  Executed sudo&lt;remove_apama_tmp_dir&gt;, exit status 0
11:02:21 INFO  
11:02:21 INFO  Test duration: 21.11 secs
11:02:21 INFO  Test final outcome:  BLOCKED
11:02:21 INFO  Test outcome reason: sudo&lt;plugin_install&gt; returned non-zero exit code 2
11:02:21 INFO  
</system-out>
	</testcase>
</testsuite><testsuite name="SoftwareManagement.sm_docker_install_remove_multiple" tests="4" errors="0" failures="2" skipped="0" time="0"><testcase classname="SMDockerInstallRemove" name="SoftwareManagement.sm_docker_install_remove_multiple" />
<testcase classname="SMDockerInstallRemove" name="SoftwareManagement.sm_docker_install_remove_multiple">
		<failure message="BLOCKED: SystemError: Timeout while waiting for status SUCCESSFUL or False" type="BLOCKED" />
		<system-out>10:28:41 INFO  ==============================================================
10:28:41 INFO  Id:    SoftwareManagement.sm_docker_install_remove_multiple
10:28:41 INFO  Dir:   software_management_end_to_end/
10:28:41 INFO  Title: Validate end to end behaviour for the docker plugin for multiple docker images with mixed versions
10:28:41 INFO  ==============================================================
10:28:42 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:28:42 INFO  EnvironmentC8y Setup
10:28:42 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:28:57 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
10:28:58 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:28:58 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:28:59 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:29:01 INFO  State of current operation: FAILED
10:29:01 INFO  Response status: 201
10:29:01 INFO  Response to action: {
    "creationTime": "2022-04-14T10:29:01.554Z",
    "deviceName": "mythicb",
    "deviceId": "17329985",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17330321",
    "id": "17330321",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '8021526', 'name': 'hello-world', 'url': '', 'version': '::docker'}, {'action': 'install', 'id': '8018911', 'name': 'registry', 'url': '', 'version': '2.6.2::docker'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "hello-world",
            "action": "install",
            "id": "8021526",
            "version": "::docker",
            "url": ""
        },
        {
            "name": "registry",
            "action": "install",
            "id": "8018911",
            "version": "2.6.2::docker",
            "url": ""
        }
    ]
}
10:29:01 INFO  Started operation: {'creationTime': '2022-04-14T10:29:01.554Z', 'deviceName': 'mythicb', 'deviceId': '17329985', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17330321', 'id': '17330321', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '8021526', 'name': 'hello-world', 'url': '', 'version': '::docker'}, {'action': 'install', 'id': '8018911', 'name': 'registry', 'url': '', 'version': '2.6.2::docker'}]", 'c8y_SoftwareUpdate': [{'name': 'hello-world', 'action': 'install', 'id': '8021526', 'version': '::docker', 'url': ''}, {'name': 'registry', 'action': 'install', 'id': '8018911', 'version': '2.6.2::docker', 'url': ''}]}
10:29:03 INFO  State of operation 17330321 : PENDING
10:29:06 INFO  State of operation 17330321 : PENDING
10:29:08 INFO  State of operation 17330321 : PENDING
10:29:10 INFO  State of operation 17330321 : PENDING
10:29:12 INFO  State of operation 17330321 : PENDING
10:29:14 INFO  State of operation 17330321 : PENDING
10:29:17 INFO  State of operation 17330321 : PENDING
10:29:19 INFO  State of operation 17330321 : PENDING
10:29:21 INFO  State of operation 17330321 : PENDING
10:29:23 INFO  State of operation 17330321 : PENDING
10:29:25 INFO  State of operation 17330321 : PENDING
10:29:28 INFO  State of operation 17330321 : PENDING
10:29:30 INFO  State of operation 17330321 : PENDING
10:29:32 INFO  State of operation 17330321 : PENDING
10:29:34 INFO  State of operation 17330321 : PENDING
10:29:37 INFO  State of operation 17330321 : PENDING
10:29:39 INFO  State of operation 17330321 : PENDING
10:29:41 INFO  State of operation 17330321 : PENDING
10:29:43 INFO  State of operation 17330321 : PENDING
10:29:45 INFO  State of operation 17330321 : PENDING
10:29:48 INFO  State of operation 17330321 : PENDING
10:29:50 INFO  State of operation 17330321 : PENDING
10:29:52 INFO  State of operation 17330321 : PENDING
10:29:54 INFO  State of operation 17330321 : PENDING
10:29:57 INFO  State of operation 17330321 : PENDING
10:29:59 INFO  State of operation 17330321 : PENDING
10:30:01 INFO  State of operation 17330321 : PENDING
10:30:03 INFO  State of operation 17330321 : PENDING
10:30:05 INFO  State of operation 17330321 : PENDING
10:30:08 INFO  State of operation 17330321 : PENDING
10:30:10 INFO  State of operation 17330321 : PENDING
10:30:12 INFO  State of operation 17330321 : PENDING
10:30:14 INFO  State of operation 17330321 : PENDING
10:30:16 INFO  State of operation 17330321 : PENDING
10:30:19 INFO  State of operation 17330321 : PENDING
10:30:21 INFO  State of operation 17330321 : PENDING
10:30:23 INFO  State of operation 17330321 : PENDING
10:30:25 INFO  State of operation 17330321 : PENDING
10:30:28 INFO  State of operation 17330321 : PENDING
10:30:30 INFO  State of operation 17330321 : PENDING
10:30:32 INFO  State of operation 17330321 : PENDING
10:30:34 INFO  State of operation 17330321 : PENDING
10:30:36 INFO  State of operation 17330321 : PENDING
10:30:39 INFO  State of operation 17330321 : PENDING
10:30:41 INFO  State of operation 17330321 : PENDING
10:30:43 INFO  State of operation 17330321 : PENDING
10:30:45 INFO  State of operation 17330321 : PENDING
10:30:48 INFO  State of operation 17330321 : PENDING
10:30:50 INFO  State of operation 17330321 : PENDING
10:30:52 INFO  State of operation 17330321 : PENDING
10:30:54 INFO  State of operation 17330321 : PENDING
10:30:56 INFO  State of operation 17330321 : PENDING
10:30:59 INFO  State of operation 17330321 : PENDING
10:31:01 INFO  State of operation 17330321 : PENDING
10:31:03 INFO  State of operation 17330321 : PENDING
10:31:05 INFO  State of operation 17330321 : PENDING
10:31:08 INFO  State of operation 17330321 : PENDING
10:31:10 INFO  State of operation 17330321 : PENDING
10:31:12 INFO  State of operation 17330321 : PENDING
10:31:14 INFO  State of operation 17330321 : PENDING
10:31:16 INFO  State of operation 17330321 : PENDING
10:31:18 WARN  SystemError occurred while running test - Timeout while waiting for status SUCCESSFUL or False
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_docker_install_remove_multiple/run.py", line 55, in setup
    self.wait_until_succcess()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 324, in wait_until_succcess
    self.wait_until_status("SUCCESSFUL")
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 381, in wait_until_status
    "Timeout while waiting for status %s or %s" % (status, status2)
SystemError: Timeout while waiting for status SUCCESSFUL or False
10:31:18 WARN  SystemError: Timeout while waiting for status SUCCESSFUL or False ... blocked 
10:31:18 INFO  
10:31:18 INFO  cleanup:
10:31:23 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:31:24 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:31:24 INFO  
10:31:24 INFO  Test duration: 163.09 secs
10:31:24 INFO  Test final outcome:  BLOCKED
10:31:24 INFO  Test outcome reason: SystemError: Timeout while waiting for status SUCCESSFUL or False
10:31:24 INFO  
</system-out>
	</testcase>
<testcase classname="SMDockerInstallRemove" name="SoftwareManagement.sm_docker_install_remove_multiple">
		<failure message="BLOCKED: SystemError: Timeout while waiting for status SUCCESSFUL or False" type="BLOCKED" />
		<system-out>10:32:32 INFO  ==============================================================
10:32:32 INFO  Id:    SoftwareManagement.sm_docker_install_remove_multiple
10:32:32 INFO  Dir:   software_management_end_to_end/
10:32:32 INFO  Title: Validate end to end behaviour for the docker plugin for multiple docker images with mixed versions
10:32:32 INFO  ==============================================================
10:32:34 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
10:32:34 INFO  EnvironmentC8y Setup
10:32:35 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
10:32:51 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 16 secs
10:32:52 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
10:32:52 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
10:32:53 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
10:32:55 INFO  State of current operation: FAILED
10:32:55 INFO  Response status: 201
10:32:55 INFO  Response to action: {
    "creationTime": "2022-04-14T10:32:55.706Z",
    "deviceName": "mythicc",
    "deviceId": "17326137",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17330323",
    "id": "17330323",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '8021526', 'name': 'hello-world', 'url': '', 'version': '::docker'}, {'action': 'install', 'id': '8018911', 'name': 'registry', 'url': '', 'version': '2.6.2::docker'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "hello-world",
            "action": "install",
            "id": "8021526",
            "version": "::docker",
            "url": ""
        },
        {
            "name": "registry",
            "action": "install",
            "id": "8018911",
            "version": "2.6.2::docker",
            "url": ""
        }
    ]
}
10:32:55 INFO  Started operation: {'creationTime': '2022-04-14T10:32:55.706Z', 'deviceName': 'mythicc', 'deviceId': '17326137', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/17330323', 'id': '17330323', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '8021526', 'name': 'hello-world', 'url': '', 'version': '::docker'}, {'action': 'install', 'id': '8018911', 'name': 'registry', 'url': '', 'version': '2.6.2::docker'}]", 'c8y_SoftwareUpdate': [{'name': 'hello-world', 'action': 'install', 'id': '8021526', 'version': '::docker', 'url': ''}, {'name': 'registry', 'action': 'install', 'id': '8018911', 'version': '2.6.2::docker', 'url': ''}]}
10:32:57 INFO  State of operation 17330323 : PENDING
10:33:00 INFO  State of operation 17330323 : PENDING
10:33:02 INFO  State of operation 17330323 : PENDING
10:33:04 INFO  State of operation 17330323 : PENDING
10:33:06 INFO  State of operation 17330323 : PENDING
10:33:09 INFO  State of operation 17330323 : PENDING
10:33:11 INFO  State of operation 17330323 : PENDING
10:33:13 INFO  State of operation 17330323 : PENDING
10:33:15 INFO  State of operation 17330323 : PENDING
10:33:17 INFO  State of operation 17330323 : PENDING
10:33:20 INFO  State of operation 17330323 : PENDING
10:33:22 INFO  State of operation 17330323 : PENDING
10:33:24 INFO  State of operation 17330323 : PENDING
10:33:26 INFO  State of operation 17330323 : PENDING
10:33:28 INFO  State of operation 17330323 : PENDING
10:33:31 INFO  State of operation 17330323 : PENDING
10:33:33 INFO  State of operation 17330323 : PENDING
10:33:35 INFO  State of operation 17330323 : PENDING
10:33:37 INFO  State of operation 17330323 : PENDING
10:33:40 INFO  State of operation 17330323 : PENDING
10:33:42 INFO  State of operation 17330323 : PENDING
10:33:44 INFO  State of operation 17330323 : PENDING
10:33:46 INFO  State of operation 17330323 : PENDING
10:33:48 INFO  State of operation 17330323 : PENDING
10:33:51 INFO  State of operation 17330323 : PENDING
10:33:53 INFO  State of operation 17330323 : PENDING
10:33:55 INFO  State of operation 17330323 : PENDING
10:33:57 INFO  State of operation 17330323 : PENDING
10:34:00 INFO  State of operation 17330323 : PENDING
10:34:02 INFO  State of operation 17330323 : PENDING
10:34:04 INFO  State of operation 17330323 : PENDING
10:34:06 INFO  State of operation 17330323 : PENDING
10:34:08 INFO  State of operation 17330323 : PENDING
10:34:11 INFO  State of operation 17330323 : PENDING
10:34:13 INFO  State of operation 17330323 : PENDING
10:34:15 INFO  State of operation 17330323 : PENDING
10:34:17 INFO  State of operation 17330323 : PENDING
10:34:19 INFO  State of operation 17330323 : PENDING
10:34:22 INFO  State of operation 17330323 : PENDING
10:34:24 INFO  State of operation 17330323 : PENDING
10:34:26 INFO  State of operation 17330323 : PENDING
10:34:28 INFO  State of operation 17330323 : PENDING
10:34:30 INFO  State of operation 17330323 : PENDING
10:34:33 INFO  State of operation 17330323 : PENDING
10:34:35 INFO  State of operation 17330323 : PENDING
10:34:37 INFO  State of operation 17330323 : PENDING
10:34:39 INFO  State of operation 17330323 : PENDING
10:34:42 INFO  State of operation 17330323 : PENDING
10:34:44 INFO  State of operation 17330323 : PENDING
10:34:46 INFO  State of operation 17330323 : PENDING
10:34:48 INFO  State of operation 17330323 : PENDING
10:34:51 INFO  State of operation 17330323 : PENDING
10:34:53 INFO  State of operation 17330323 : PENDING
10:34:55 INFO  State of operation 17330323 : PENDING
10:34:57 INFO  State of operation 17330323 : PENDING
10:34:59 INFO  State of operation 17330323 : PENDING
10:35:02 INFO  State of operation 17330323 : PENDING
10:35:04 INFO  State of operation 17330323 : PENDING
10:35:06 INFO  State of operation 17330323 : PENDING
10:35:08 INFO  State of operation 17330323 : PENDING
10:35:10 INFO  State of operation 17330323 : PENDING
10:35:12 WARN  SystemError occurred while running test - Timeout while waiting for status SUCCESSFUL or False
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1292, in __call__
    self.testObj.setup()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_docker_install_remove_multiple/run.py", line 55, in setup
    self.wait_until_succcess()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 324, in wait_until_succcess
    self.wait_until_status("SUCCESSFUL")
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 381, in wait_until_status
    "Timeout while waiting for status %s or %s" % (status, status2)
SystemError: Timeout while waiting for status SUCCESSFUL or False
10:35:13 WARN  SystemError: Timeout while waiting for status SUCCESSFUL or False ... blocked 
10:35:13 INFO  
10:35:13 INFO  cleanup:
10:35:17 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:35:18 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
10:35:18 INFO  
10:35:18 INFO  Test duration: 166.09 secs
10:35:18 INFO  Test final outcome:  BLOCKED
10:35:18 INFO  Test outcome reason: SystemError: Timeout while waiting for status SUCCESSFUL or False
10:35:18 INFO  
</system-out>
	</testcase>
<testcase classname="SMDockerInstallRemove" name="SoftwareManagement.sm_docker_install_remove_multiple" />
</testsuite><testsuite name="docker_plugin_finalize" tests="4" errors="0" failures="1" skipped="0" time="0"><testcase classname="DockerPluginFinalizeTest" name="docker_plugin_finalize" />
<testcase classname="DockerPluginFinalizeTest" name="docker_plugin_finalize">
		<failure message="FAILED: Grep on /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_finalize/Output/linux/docker_images.out does not contain &quot;registry&quot; failed with 2 matches, first is: &quot;registry            2.7.1               e8a56425636e        5 months ago        22.2MB&quot;" type="FAILED" />
		<system-out>10:28:34 INFO  ==============================================================
10:28:34 INFO  Id:    docker_plugin_finalize
10:28:34 INFO  Dir:   plugin_docker/
10:28:34 INFO  Title: Validate docker plugin finalize command
10:28:34 INFO  ==============================================================
10:28:35 INFO  Executed sudo&lt;docker_images&gt;, exit status 0
10:28:36 WARN  Grep on /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_finalize/Output/linux/docker_images.out does not contain "registry" failed with 2 matches, first is: "registry            2.7.1               e8a56425636e        5 months ago        22.2MB" ... failed 
10:28:36 WARN  Aborted test due to FAILED outcome
10:28:36 INFO  
10:28:36 INFO  cleanup:
10:28:36 INFO  
10:28:36 INFO  Test duration: 1.25 secs
10:28:36 INFO  Test final outcome:  FAILED
10:28:36 INFO  Test outcome reason: Grep on /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_finalize/Output/linux/docker_images.out does not contain "registry" failed with 2 matches, first is: "registry            2.7.1               e8a56425636e        5 months ago        22.2MB"
10:28:36 INFO  
</system-out>
	</testcase>
<testcase classname="DockerPluginFinalizeTest" name="docker_plugin_finalize" />
<testcase classname="DockerPluginFinalizeTest" name="docker_plugin_finalize" />
</testsuite><testsuite name="docker_plugin_install" tests="4" errors="0" failures="1" skipped="0" time="0"><testcase classname="DockerPluginInstallTest" name="docker_plugin_install" />
<testcase classname="DockerPluginInstallTest" name="docker_plugin_install">
		<failure message="FAILED: Grep on /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_install/Output/linux/docker_images.out does not contain &quot;registry&quot; failed with 2 matches, first is: &quot;registry            2.7.1               e8a56425636e        5 months ago        22.2MB&quot;" type="FAILED" />
		<system-out>10:28:36 INFO  ==============================================================
10:28:36 INFO  Id:    docker_plugin_install
10:28:36 INFO  Dir:   plugin_docker/
10:28:36 INFO  Title: Validate docker plugin install
10:28:36 INFO  ==============================================================
10:28:36 INFO  Executed sudo&lt;docker_images&gt;, exit status 0
10:28:36 WARN  Grep on /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_install/Output/linux/docker_images.out does not contain "registry" failed with 2 matches, first is: "registry            2.7.1               e8a56425636e        5 months ago        22.2MB" ... failed 
10:28:36 WARN  Aborted test due to FAILED outcome
10:28:36 INFO  
10:28:36 INFO  cleanup:
10:28:36 INFO  
10:28:36 INFO  Test duration: 0.89 secs
10:28:36 INFO  Test final outcome:  FAILED
10:28:36 INFO  Test outcome reason: Grep on /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_install/Output/linux/docker_images.out does not contain "registry" failed with 2 matches, first is: "registry            2.7.1               e8a56425636e        5 months ago        22.2MB"
10:28:36 INFO  
</system-out>
	</testcase>
<testcase classname="DockerPluginInstallTest" name="docker_plugin_install" />
<testcase classname="DockerPluginInstallTest" name="docker_plugin_install" />
</testsuite><testsuite name="docker_plugin_install_with_version" tests="4" errors="0" failures="1" skipped="0" time="0"><testcase classname="DockerPluginInstallWithVersionTest" name="docker_plugin_install_with_version" />
<testcase classname="DockerPluginInstallWithVersionTest" name="docker_plugin_install_with_version">
		<failure message="FAILED: Grep on /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_install_with_version/Output/linux/docker_images.out does not contain &quot;registry&quot; failed with 2 matches, first is: &quot;registry            2.7.1               e8a56425636e        5 months ago        22.2MB&quot;" type="FAILED" />
		<system-out>10:28:37 INFO  ==============================================================
10:28:37 INFO  Id:    docker_plugin_install_with_version
10:28:37 INFO  Dir:   plugin_docker/
10:28:37 INFO  Title: Validate docker plugin install
10:28:37 INFO  ==============================================================
10:28:37 INFO  Executed sudo&lt;docker_images&gt;, exit status 0
10:28:37 WARN  Grep on /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_install_with_version/Output/linux/docker_images.out does not contain "registry" failed with 2 matches, first is: "registry            2.7.1               e8a56425636e        5 months ago        22.2MB" ... failed 
10:28:37 WARN  Aborted test due to FAILED outcome
10:28:37 INFO  
10:28:37 INFO  cleanup:
10:28:37 INFO  
10:28:37 INFO  Test duration: 0.88 secs
10:28:37 INFO  Test final outcome:  FAILED
10:28:37 INFO  Test outcome reason: Grep on /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_install_with_version/Output/linux/docker_images.out does not contain "registry" failed with 2 matches, first is: "registry            2.7.1               e8a56425636e        5 months ago        22.2MB"
10:28:37 INFO  
</system-out>
	</testcase>
<testcase classname="DockerPluginInstallWithVersionTest" name="docker_plugin_install_with_version" />
<testcase classname="DockerPluginInstallWithVersionTest" name="docker_plugin_install_with_version" />
</testsuite><testsuite name="docker_plugin_remove" tests="4" errors="0" failures="1" skipped="0" time="0"><testcase classname="DockerPluginRemoveTest" name="docker_plugin_remove" />
<testcase classname="DockerPluginRemoveTest" name="docker_plugin_remove">
		<failure message="FAILED: Grep on /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_remove/Output/linux/docker_images.out does not contain &quot;registry&quot; failed with 2 matches, first is: &quot;registry            2.7.1               e8a56425636e        5 months ago        22.2MB&quot;" type="FAILED" />
		<system-out>10:28:37 INFO  ==============================================================
10:28:37 INFO  Id:    docker_plugin_remove
10:28:37 INFO  Dir:   plugin_docker/
10:28:37 INFO  Title: Validate docker plugin remove
10:28:37 INFO  ==============================================================
10:28:38 INFO  Executed sudo&lt;docker_images&gt;, exit status 0
10:28:38 WARN  Grep on /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_remove/Output/linux/docker_images.out does not contain "registry" failed with 2 matches, first is: "registry            2.7.1               e8a56425636e        5 months ago        22.2MB" ... failed 
10:28:38 WARN  Aborted test due to FAILED outcome
10:28:38 INFO  
10:28:38 INFO  cleanup:
10:28:38 INFO  
10:28:38 INFO  Test duration: 0.89 secs
10:28:38 INFO  Test final outcome:  FAILED
10:28:38 INFO  Test outcome reason: Grep on /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_remove/Output/linux/docker_images.out does not contain "registry" failed with 2 matches, first is: "registry            2.7.1               e8a56425636e        5 months ago        22.2MB"
10:28:38 INFO  
</system-out>
	</testcase>
<testcase classname="DockerPluginRemoveTest" name="docker_plugin_remove" />
<testcase classname="DockerPluginRemoveTest" name="docker_plugin_remove" />
</testsuite><testsuite name="docker_plugin_remove_with_version" tests="4" errors="0" failures="1" skipped="0" time="0"><testcase classname="DockerPluginRemoveWithVersionTest" name="docker_plugin_remove_with_version" />
<testcase classname="DockerPluginRemoveWithVersionTest" name="docker_plugin_remove_with_version">
		<failure message="FAILED: Grep on /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_remove_with_version/Output/linux/docker_images.out does not contain &quot;registry&quot; failed with 2 matches, first is: &quot;registry            2.7.1               e8a56425636e        5 months ago        22.2MB&quot;" type="FAILED" />
		<system-out>10:28:38 INFO  ==============================================================
10:28:38 INFO  Id:    docker_plugin_remove_with_version
10:28:38 INFO  Dir:   plugin_docker/
10:28:38 INFO  Title: Validate docker plugin remove with version
10:28:38 INFO  ==============================================================
10:28:39 INFO  Executed sudo&lt;docker_images&gt;, exit status 0
10:28:39 WARN  Grep on /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_remove_with_version/Output/linux/docker_images.out does not contain "registry" failed with 2 matches, first is: "registry            2.7.1               e8a56425636e        5 months ago        22.2MB" ... failed 
10:28:39 WARN  Aborted test due to FAILED outcome
10:28:39 INFO  
10:28:39 INFO  cleanup:
10:28:39 INFO  
10:28:39 INFO  Test duration: 1.07 secs
10:28:39 INFO  Test final outcome:  FAILED
10:28:39 INFO  Test outcome reason: Grep on /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_remove_with_version/Output/linux/docker_images.out does not contain "registry" failed with 2 matches, first is: "registry            2.7.1               e8a56425636e        5 months ago        22.2MB"
10:28:39 INFO  
</system-out>
	</testcase>
<testcase classname="DockerPluginRemoveWithVersionTest" name="docker_plugin_remove_with_version" />
<testcase classname="DockerPluginRemoveWithVersionTest" name="docker_plugin_remove_with_version" />
</testsuite><testsuite name="docker_plugin_update" tests="4" errors="0" failures="1" skipped="0" time="0"><testcase classname="DockerPluginUpdateTest" name="docker_plugin_update" />
<testcase classname="DockerPluginUpdateTest" name="docker_plugin_update">
		<failure message="FAILED: Grep on /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_images.out does not contain &quot;registry&quot; failed with 2 matches, first is: &quot;registry            2.7.1               e8a56425636e        5 months ago        22.2MB&quot;" type="FAILED" />
		<system-out>10:28:39 INFO  ==============================================================
10:28:39 INFO  Id:    docker_plugin_update
10:28:39 INFO  Dir:   plugin_docker/
10:28:39 INFO  Title: Validate docker plugin install updates existing containers
10:28:39 INFO  ==============================================================
10:28:40 INFO  Executed sudo&lt;docker_images&gt;, exit status 0
10:28:40 WARN  Grep on /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_images.out does not contain "registry" failed with 2 matches, first is: "registry            2.7.1               e8a56425636e        5 months ago        22.2MB" ... failed 
10:28:40 WARN  Aborted test due to FAILED outcome
10:28:40 INFO  
10:28:40 INFO  cleanup:
10:28:40 INFO  
10:28:40 INFO  Test duration: 1.05 secs
10:28:40 INFO  Test final outcome:  FAILED
10:28:40 INFO  Test outcome reason: Grep on /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_images.out does not contain "registry" failed with 2 matches, first is: "registry            2.7.1               e8a56425636e        5 months ago        22.2MB"
10:28:40 INFO  
</system-out>
	</testcase>
<testcase classname="DockerPluginUpdateTest" name="docker_plugin_update" />
<testcase classname="DockerPluginUpdateTest" name="docker_plugin_update" />
</testsuite></testsuites>