2022-03-28 19:44:46,535 INFO  ==============================================================
2022-03-28 19:44:46,536 INFO  Id:    runtime_start_two_mappers
2022-03-28 19:44:46,536 INFO  Dir:   tedge_mapper_c8y/
2022-03-28 19:44:46,537 INFO  Title: Validate two mappers can't be started at the same time
2022-03-28 19:44:46,537 DEBUG Execution order hint: 0.0
2022-03-28 19:44:46,538 INFO  ==============================================================
2022-03-28 19:44:46,541 DEBUG --- test execute
2022-03-28 19:44:46,543 DEBUG Process parameters for sudo<tedge_mapper1>
  command line : /usr/bin/sudo systemctl start tedge-mapper-c8y
    arg #1     : systemctl
    arg #2     : start
    arg #3     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_mapper_c8y/runtime_start_two_mappers/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_mapper_c8y/runtime_start_two_mappers/Output/linux/tedge_mapper1.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_mapper_c8y/runtime_start_two_mappers/Output/linux/tedge_mapper1.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-28 19:44:46,548 DEBUG Waiting up to 600 secs for process sudo<tedge_mapper1> (pid 19840)
2022-03-28 19:44:46,802 INFO  Executed sudo<tedge_mapper1>, exit status 0
2022-03-28 19:44:46,802 INFO  Waiting for 0.1 seconds
2022-03-28 19:44:46,904 DEBUG Process parameters for sudo<tedge_mapper2>
  command line : /usr/bin/sudo -u tedge-mapper /usr/bin/tedge_mapper c8y
    arg #1     : -u
    arg #2     : tedge-mapper
    arg #3     : /usr/bin/tedge_mapper
    arg #4     : c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_mapper_c8y/runtime_start_two_mappers/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_mapper_c8y/runtime_start_two_mappers/Output/linux/tedge_mapper2.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_mapper_c8y/runtime_start_two_mappers/Output/linux/tedge_mapper2.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-28 19:44:46,909 DEBUG Waiting up to 600 secs for process sudo<tedge_mapper2> (pid 19847)
2022-03-28 19:44:47,163 INFO  Executed sudo<tedge_mapper2>, exit status 1
2022-03-28 19:44:47,164 DEBUG Process parameters for sudo<tedge_mapper1>
  command line : /usr/bin/sudo systemctl stop tedge-mapper-c8y
    arg #1     : systemctl
    arg #2     : stop
    arg #3     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_mapper_c8y/runtime_start_two_mappers/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_mapper_c8y/runtime_start_two_mappers/Output/linux/tedge_mapper1.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_mapper_c8y/runtime_start_two_mappers/Output/linux/tedge_mapper1.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-28 19:44:47,169 DEBUG Waiting up to 600 secs for process sudo<tedge_mapper1> (pid 19853)
2022-03-28 19:44:47,423 INFO  Executed sudo<tedge_mapper1>, exit status 0
2022-03-28 19:44:47,424 DEBUG --- test validate
2022-03-28 19:44:47,424 DEBUG Performing regex contains=True grep on file: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_mapper_c8y/runtime_start_two_mappers/Output/linux/tedge_mapper2.err
2022-03-28 19:44:47,426 DEBUG Grep on file tedge_mapper2.err successfully matched expression "Error: Couldn't acquire file lock." with line: "Error: Couldn't acquire file lock.\n"
2022-03-28 19:44:47,427 INFO  Grep on file tedge_mapper2.err ... passed
2022-03-28 19:44:47,428 DEBUG --- test cleanup
2022-03-28 19:44:47,429 DEBUG ProcessUser cleanup function done.
2022-03-28 19:44:47,430 INFO  
2022-03-28 19:44:47,431 INFO  Test duration: 0.89 secs
2022-03-28 19:44:47,431 INFO  Test final outcome:  PASSED
2022-03-28 19:44:47,432 INFO  
