2022-04-07 17:20:48,909 INFO  ==============================================================
2022-04-07 17:20:48,910 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_update
2022-04-07 17:20:48,911 INFO  Dir:   plugin_apama/
2022-04-07 17:20:48,912 INFO  Title: Validate apama plugin updating one project with another
2022-04-07 17:20:48,914 DEBUG Execution order hint: 0.0
2022-04-07 17:20:48,915 INFO  ==============================================================
2022-04-07 17:20:48,974 WARN  Assertion that path exists=False for "/etc/tedge/apama/project" ... failed 
2022-04-07 17:20:48,975 WARN  Aborted test due to FAILED outcome
2022-04-07 17:20:48,980 DEBUG --- test cleanup
2022-04-07 17:20:48,982 INFO  
2022-04-07 17:20:48,983 INFO  cleanup:
2022-04-07 17:20:48,984 DEBUG Running registered cleanup function: <bound method ApamaPlugin.cleanup_project of <ApamaPluginUpdateTest object at 0x7605a730>>
2022-04-07 17:20:48,985 INFO  Removing apama project
2022-04-07 17:20:48,987 DEBUG Process parameters for sudo<remove_apama_project>
  command line : /usr/bin/sudo rm -rf /etc/tedge/apama/project
    arg #1     : rm
    arg #2     : -rf
    arg #3     : /etc/tedge/apama/project
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/apama_plugin_update/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/apama_plugin_update/Output/linux/remove_apama_project.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/apama_plugin_update/Output/linux/remove_apama_project.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-04-07 17:20:48,995 DEBUG Waiting up to 600 secs for process sudo<remove_apama_project> (pid 9523)
2022-04-07 17:20:49,604 WARN  Executed sudo<remove_apama_project>, exit status 1
2022-04-07 17:20:49,606 DEBUG Opening file using encoding=UTF-8: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/apama_plugin_update/Output/linux/remove_apama_project.err
2022-04-07 17:20:49,610 INFO  Contents of remove_apama_project.err: 
2022-04-07 17:20:49,611 INFO    rm: cannot remove '/etc/tedge/apama/project/logs/.nfs00000000000a024100007ea2': Device or resource busy
2022-04-07 17:20:49,612 INFO    -----
2022-04-07 17:20:49,613 INFO  
2022-04-07 17:20:49,648 ERROR Error while running cleanup function: 
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1305, in cleanup
    fn()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/environment_apama_plugin.py", line 144, in cleanup_project
    self.remove_project()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/environment_apama_plugin.py", line 95, in remove_project
    stdouterr="remove_apama_project",
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 482, in startProcess
    abortOnError=abortOnError)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1401, in addOutcome
    self.abort(outcome, outcomeReason, callRecord)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1420, in abort
    raise AbortExecution(outcome, outcomeReason, callRecord)
pysys.exceptions.AbortExecution: sudo<remove_apama_project> returned non-zero exit code 1
2022-04-07 17:20:49,653 DEBUG ProcessUser cleanup function done.
2022-04-07 17:20:49,667 WARN  Cleanup failed with 1 errors: Cleanup function failed: sudo<remove_apama_project> returned non-zero exit code 1 (AbortExecution) ... blocked 
2022-04-07 17:20:49,671 INFO  
2022-04-07 17:20:49,672 INFO  Test duration: 0.77 secs
2022-04-07 17:20:49,673 INFO  Test final outcome:  BLOCKED
2022-04-07 17:20:49,675 INFO  Test outcome reason: sudo<remove_apama_project> returned non-zero exit code 1 (+2 other failures)
2022-04-07 17:20:49,677 INFO  
