2022-04-13 07:59:09,117 INFO  ==============================================================
2022-04-13 07:59:09,118 INFO  Id:    tedge_mapper_c8y_alarms
2022-04-13 07:59:09,119 INFO  Dir:   tedge_mapper_c8y/
2022-04-13 07:59:09,120 INFO  Title: Validate that alarms sent to tedge/alarms topic \ gets mapped as alarms in Cumulocity
2022-04-13 07:59:09,120 INFO  ==============================================================
2022-04-13 07:59:09,129 INFO  EnvironmentC8y Setup
2022-04-13 07:59:09,743 INFO  Executed systemctl<serv_mapper1>, exit status 3
2022-04-13 07:59:24,265 INFO  Executed sudo<tedge_connect_c8y>, exit status 0, duration 14 secs
2022-04-13 07:59:24,887 INFO  Executed sudo<tedge_connect_c8y_test>, exit status 0
2022-04-13 07:59:25,351 INFO  Executed systemctl<serv_mosq2>, exit status 0
2022-04-13 07:59:25,814 INFO  Executed systemctl<serv_mapper3>, exit status 0
2022-04-13 07:59:31,231 INFO  Executed tedge, exit status 0
2022-04-13 07:59:31,643 INFO  Executed tedge, exit status 0
2022-04-13 07:59:32,055 INFO  Executed tedge, exit status 0
2022-04-13 07:59:32,466 INFO  Executed tedge, exit status 0
2022-04-13 07:59:32,928 INFO  Executed tedge, exit status 0
2022-04-13 07:59:34,143 WARN  IndexError occurred while running test - list index out of range
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1296, in __call__
    self.testObj.validate()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_mapper_c8y/tedge_mapper_c8y_alarms/run.py", line 100, in validate
    alarms[0],
IndexError: list index out of range
2022-04-13 07:59:34,166 WARN  IndexError: list index out of range ... blocked 
2022-04-13 07:59:34,167 INFO  
2022-04-13 07:59:34,168 INFO  cleanup:
2022-04-13 07:59:34,579 INFO  Executed tedge, exit status 0
2022-04-13 07:59:34,991 INFO  Executed tedge, exit status 0
2022-04-13 07:59:35,405 INFO  Executed tedge, exit status 0
2022-04-13 07:59:39,526 INFO  Executed sudo<tedge_disconnect_c8y>, exit status 0
2022-04-13 07:59:40,206 INFO  Executed systemctl<serv_mapper5>, exit status 3
2022-04-13 07:59:40,211 INFO  
2022-04-13 07:59:40,213 INFO  Test duration: 31.10 secs
2022-04-13 07:59:40,215 INFO  Test final outcome:  BLOCKED
2022-04-13 07:59:40,217 INFO  Test outcome reason: IndexError: list index out of range
2022-04-13 07:59:40,218 INFO  
