2022-04-04 08:31:10,942 INFO  ==============================================================
2022-04-04 08:31:10,942 INFO  Id:    tedge_connect_test_negative
2022-04-04 08:31:10,943 INFO  Dir:   tedge_connect/
2022-04-04 08:31:10,943 INFO  Title: Validate tedge connect c8y --test (negative case)
2022-04-04 08:31:10,944 DEBUG Execution order hint: 0.0
2022-04-04 08:31:10,944 INFO  ==============================================================
2022-04-04 08:31:10,947 DEBUG --- test execute
2022-04-04 08:31:10,947 INFO  Execute `tedge connect c8y --test`
2022-04-04 08:31:10,948 DEBUG Process parameters for sudo<tedge_connect_c8y_test>
  command line : /usr/bin/sudo /usr/bin/tedge connect c8y --test
    arg #1     : /usr/bin/tedge
    arg #2     : connect
    arg #3     : c8y
    arg #4     : --test
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_negative/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_negative/Output/linux/tedge_connect_c8y_test.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_negative/Output/linux/tedge_connect_c8y_test.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-04-04 08:31:10,954 DEBUG Waiting up to 600 secs for process sudo<tedge_connect_c8y_test> (pid 18413)
2022-04-04 08:31:11,258 INFO  Executed sudo<tedge_connect_c8y_test>, exit status 1
2022-04-04 08:31:11,260 DEBUG --- test validate
2022-04-04 08:31:11,260 INFO  Validate
2022-04-04 08:31:11,261 DEBUG Performing regex contains=True grep on file: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_negative/Output/linux/tedge_connect_c8y_test.err
2022-04-04 08:31:11,268 DEBUG Grep on file tedge_connect_c8y_test.err successfully matched expression "Error: failed to test connection to Cumulocity cloud." with line: 'Error: failed to test connection to Cumulocity cloud.\n'
2022-04-04 08:31:11,269 INFO  Grep on file tedge_connect_c8y_test.err ... passed
2022-04-04 08:31:11,274 DEBUG --- test cleanup
2022-04-04 08:31:11,275 DEBUG ProcessUser cleanup function done.
2022-04-04 08:31:11,278 INFO  
2022-04-04 08:31:11,279 INFO  Test duration: 0.34 secs
2022-04-04 08:31:11,280 INFO  Test final outcome:  PASSED
2022-04-04 08:31:11,280 INFO  
