<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="SoftwareManagement.sm_mapper_fail_and_reconnect" skipped="0" tests="1" time="0.02" timestamp="2022-02-25T16:44:31">
	<testcase classname="SmMapperC8yReceiveLastMessageOnRestart" name="SoftwareManagement.sm_mapper_fail_and_reconnect">
		<failure message="BLOCKED: Failed to set up test: name 'BaseTest' is not defined" type="BLOCKED"/>
		<system-out>16:44:31 INFO  ==============================================================
16:44:31 INFO  Id:    SoftwareManagement.sm_mapper_fail_and_reconnect
16:44:31 INFO  Dir:   software_management_end_to_end/
16:44:31 INFO  Title: Validate the tedge-mapper-sm-c8y for receiving the last message on restart
16:44:31 DEBUG Execution order hint: 0.0
16:44:31 INFO  ==============================================================
16:44:31 WARN  Failed to set up test: name 'BaseTest' is not defined ... blocked 
16:44:31 WARN  caught &lt;class 'NameError'&gt; while setting up test SoftwareManagement.sm_mapper_fail_and_reconnect: name 'BaseTest' is not defined
Traceback (most recent call last):
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py&quot;, line 1143, in __call__
    exec(runpycode, runpy_namespace)
  File &quot;/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_mapper_fail_and_reconnect/run.py&quot;, line 27, in &lt;module&gt;
    class SmMapperC8yReceiveLastMessageOnRestart(BaseTest):
NameError: name 'BaseTest' is not defined
16:44:31 DEBUG --- test cleanup
16:44:31 DEBUG ProcessUser cleanup function done.
16:44:31 INFO  
16:44:31 INFO  Test duration: 0.02 secs
16:44:31 INFO  Test final outcome:  BLOCKED
16:44:31 INFO  Test outcome reason: Failed to set up test: name 'BaseTest' is not defined
16:44:31 INFO  
</system-out>
	</testcase>
</testsuite>
