<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="0" name="monitoring_with_collectd" skipped="1" tests="1" time="0.05" timestamp="2022-04-07T16:15:22">
	<testcase classname="MonitoringWithCollectd" name="monitoring_with_collectd">
		<skipped message="SKIPPED: Test execution disabled due to #792 (instable)"/>
		<system-out>16:15:22 DEBUG deletedir failed to update permissions and delete /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/monitoring/monitoring_with_collectd/Output/linux on this attempt: [Errno 2] No such file or directory: '/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/monitoring/monitoring_with_collectd/Output/linux'
16:15:22 INFO  ==============================================================
16:15:22 INFO  Id:    monitoring_with_collectd
16:15:22 INFO  Dir:   monitoring/
16:15:22 INFO  Title: Validate tedge dm agent messages that are produced by batching the collectd messages
16:15:22 DEBUG Execution order hint: 0.0
16:15:22 INFO  ==============================================================
16:15:22 INFO  Test execution disabled due to #792 (instable) ... skipped
16:15:22 DEBUG --- test cleanup
16:15:22 DEBUG ProcessUser cleanup function done.
16:15:22 INFO  
16:15:22 INFO  Test duration: 0.05 secs
16:15:22 INFO  Test final outcome:  SKIPPED
16:15:22 INFO  Test outcome reason: Test execution disabled due to #792 (instable)
16:15:22 INFO  
</system-out>
	</testcase>
</testsuite>
