2022-02-22 11:21:15,058 INFO  ==============================================================
2022-02-22 11:21:15,059 INFO  Id:    tedge_connect_test_sm_services
2022-02-22 11:21:15,060 INFO  Dir:   tedge_connect/
2022-02-22 11:21:15,060 INFO  Title: Validate Software Management Services started and enabled on tedge connect c8y
2022-02-22 11:21:15,061 DEBUG Execution order hint: 0.0
2022-02-22 11:21:15,061 INFO  ==============================================================
2022-02-22 11:21:15,103 DEBUG EnvironmentC8y Setup
2022-02-22 11:21:15,104 INFO  EnvironmentC8y Setup
2022-02-22 11:21:15,106 DEBUG Process parameters for systemctl<serv_mapper1>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper1.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper1.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-22 11:21:15,114 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper1> (pid 8908)
2022-02-22 11:21:15,419 INFO  Executed systemctl<serv_mapper1>, exit status 3
2022-02-22 11:21:15,502 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 2 seconds
2022-02-22 11:21:15,503 INFO  Delaying execution by 9 seconds
2022-02-22 11:21:24,519 DEBUG Process parameters for sudo<tedge_connect_c8y>
  command line : /usr/bin/sudo /usr/bin/tedge connect c8y
    arg #1     : /usr/bin/tedge
    arg #2     : connect
    arg #3     : c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect_c8y.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect_c8y.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-22 11:21:24,525 DEBUG Waiting up to 600 secs for process sudo<tedge_connect_c8y> (pid 8912)
2022-02-22 11:21:34,519 INFO  Executed sudo<tedge_connect_c8y>, exit status 0
2022-02-22 11:21:34,523 DEBUG Process parameters for sudo<tedge_connect_c8y_test>
  command line : /usr/bin/sudo /usr/bin/tedge connect c8y --test
    arg #1     : /usr/bin/tedge
    arg #2     : connect
    arg #3     : c8y
    arg #4     : --test
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect_c8y_test.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect_c8y_test.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-22 11:21:34,529 DEBUG Waiting up to 600 secs for process sudo<tedge_connect_c8y_test> (pid 9014)
2022-02-22 11:21:34,884 INFO  Executed sudo<tedge_connect_c8y_test>, exit status 0
2022-02-22 11:21:34,886 DEBUG Process parameters for systemctl<serv_mosq2>
  command line : /usr/bin/systemctl status mosquitto
    arg #1     : status
    arg #2     : mosquitto
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mosq2.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mosq2.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-22 11:21:34,890 DEBUG Waiting up to 600 secs for process systemctl<serv_mosq2> (pid 9019)
2022-02-22 11:21:35,145 INFO  Executed systemctl<serv_mosq2>, exit status 0
2022-02-22 11:21:35,146 DEBUG Process parameters for systemctl<serv_mapper3>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper3.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper3.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-22 11:21:35,151 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper3> (pid 9020)
2022-02-22 11:21:35,419 INFO  Executed systemctl<serv_mapper3>, exit status 0
2022-02-22 11:21:35,420 DEBUG --- test execute
2022-02-22 11:21:35,420 DEBUG EnvironmentC8y Execute
2022-02-22 11:21:35,420 DEBUG --- test validate
2022-02-22 11:21:35,421 DEBUG EnvironmentC8y Validate
2022-02-22 11:21:35,422 DEBUG Process parameters for systemctl<serv_mosq>
  command line : /usr/bin/systemctl status mosquitto
    arg #1     : status
    arg #2     : mosquitto
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mosq.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mosq.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-22 11:21:35,427 DEBUG Waiting up to 600 secs for process systemctl<serv_mosq> (pid 9021)
2022-02-22 11:21:35,681 INFO  Executed systemctl<serv_mosq>, exit status 0
2022-02-22 11:21:35,683 DEBUG Process parameters for systemctl<serv_mapper4>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper4.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper4.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-22 11:21:35,688 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper4> (pid 9022)
2022-02-22 11:21:35,943 INFO  Executed systemctl<serv_mapper4>, exit status 0
2022-02-22 11:21:35,944 INFO  Validate
2022-02-22 11:21:35,945 DEBUG Performing regex contains=True grep on file: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect_c8y.out
2022-02-22 11:21:35,952 DEBUG Grep on input file tedge_connect_c8y.out successfully matched expression "tedge-agent service successfully started and enabled!" with line: 'tedge-agent service successfully started and enabled!\n'
2022-02-22 11:21:35,954 INFO  Grep on input file tedge_connect_c8y.out ... passed
2022-02-22 11:21:35,955 DEBUG Performing regex contains=True grep on file: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect.out
2022-02-22 11:21:35,959 WARN  caught <class 'pysys.exceptions.FileNotFoundException'>: unable to find file "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect.out"
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/basetest.py", line 1203, in assertGrep
    result = getmatches(f, expr, ignores=ignores, returnFirstOnly=(contains==True), encoding=encoding or self.getDefaultFileEncoding(f), flags=reFlags, mappers=mappers)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/utils/filegrep.py", line 59, in getmatches
    raise FileNotFoundException("unable to find file \"%s\"" % (file))
pysys.exceptions.FileNotFoundException: unable to find file "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect.out"
2022-02-22 11:21:36,003 WARN  Grep on tedge_connect.out contains "tedge-mapper-c8y service successfully started and enabled!" failed due to <class 'pysys.exceptions.FileNotFoundException'>: unable to find file "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect.out" ... blocked [run.py:37]
2022-02-22 11:21:36,008 DEBUG --- test cleanup
2022-02-22 11:21:36,009 INFO  
2022-02-22 11:21:36,009 INFO  cleanup:
2022-02-22 11:21:36,010 DEBUG Running registered cleanup function: <bound method EnvironmentC8y.myenvcleanup of <TedgeConnectTestSMServices object at 0x75af1d70>>
2022-02-22 11:21:36,010 DEBUG EnvironmentC8y Cleanup
2022-02-22 11:21:36,086 DEBUG Process parameters for sudo<tedge_disconnect_c8y>
  command line : /usr/bin/sudo /usr/bin/tedge disconnect c8y
    arg #1     : /usr/bin/tedge
    arg #2     : disconnect
    arg #3     : c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_disconnect_c8y.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_disconnect_c8y.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-22 11:21:36,091 DEBUG Waiting up to 600 secs for process sudo<tedge_disconnect_c8y> (pid 9028)
2022-02-22 11:21:38,521 INFO  Executed sudo<tedge_disconnect_c8y>, exit status 0
2022-02-22 11:21:38,522 DEBUG Process parameters for systemctl<serv_mapper5>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper5.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper5.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-22 11:21:38,527 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper5> (pid 9066)
2022-02-22 11:21:38,831 INFO  Executed systemctl<serv_mapper5>, exit status 3
2022-02-22 11:21:38,833 DEBUG ProcessUser cleanup function done.
2022-02-22 11:21:38,835 INFO  
2022-02-22 11:21:38,836 INFO  Test duration: 23.78 secs
2022-02-22 11:21:38,837 INFO  Test final outcome:  BLOCKED
2022-02-22 11:21:38,838 INFO  Test outcome reason: Grep on tedge_connect.out contains "tedge-mapper-c8y service successfully started and enabled!" failed due to <class 'pysys.exceptions.FileNotFoundException'>: unable to find file "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect.out"
2022-02-22 11:21:38,839 INFO  
