2022-02-18 15:23:38,229 INFO  ==============================================================
2022-02-18 15:23:38,230 INFO  Id:    tedge_connect_test_sm_services
2022-02-18 15:23:38,231 INFO  Dir:   tedge_connect/
2022-02-18 15:23:38,231 INFO  Title: Validate Software Management Services started and enabled on tedge connect c8y
2022-02-18 15:23:38,231 DEBUG Execution order hint: 0.0
2022-02-18 15:23:38,232 INFO  ==============================================================
2022-02-18 15:23:38,234 DEBUG EnvironmentC8y Setup
2022-02-18 15:23:38,235 INFO  EnvironmentC8y Setup
2022-02-18 15:23:38,236 DEBUG Process parameters for systemctl<serv_mapper1>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper1.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper1.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-18 15:23:38,241 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper1> (pid 29433)
2022-02-18 15:23:38,546 INFO  Executed systemctl<serv_mapper1>, exit status 3
2022-02-18 15:23:38,642 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 2 seconds
2022-02-18 15:23:38,643 INFO  Delaying execution by 9 seconds
2022-02-18 15:23:47,658 DEBUG Process parameters for sudo<tedge_connect_c8y>
  command line : /usr/bin/sudo /usr/bin/tedge connect c8y
    arg #1     : /usr/bin/tedge
    arg #2     : connect
    arg #3     : c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect_c8y.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect_c8y.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-18 15:23:47,667 DEBUG Waiting up to 600 secs for process sudo<tedge_connect_c8y> (pid 29438)
2022-02-18 15:23:57,725 INFO  Executed sudo<tedge_connect_c8y>, exit status 0
2022-02-18 15:23:57,729 DEBUG Process parameters for sudo<tedge_connect_c8y_test>
  command line : /usr/bin/sudo /usr/bin/tedge connect c8y --test
    arg #1     : /usr/bin/tedge
    arg #2     : connect
    arg #3     : c8y
    arg #4     : --test
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect_c8y_test.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect_c8y_test.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-18 15:23:57,736 DEBUG Waiting up to 600 secs for process sudo<tedge_connect_c8y_test> (pid 29531)
2022-02-18 15:23:58,142 INFO  Executed sudo<tedge_connect_c8y_test>, exit status 0
2022-02-18 15:23:58,163 DEBUG Process parameters for systemctl<serv_mosq2>
  command line : /usr/bin/systemctl status mosquitto
    arg #1     : status
    arg #2     : mosquitto
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mosq2.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mosq2.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-18 15:23:58,170 DEBUG Waiting up to 600 secs for process systemctl<serv_mosq2> (pid 29534)
2022-02-18 15:23:58,424 INFO  Executed systemctl<serv_mosq2>, exit status 0
2022-02-18 15:23:58,426 DEBUG Process parameters for systemctl<serv_mapper3>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper3.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper3.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-18 15:23:58,433 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper3> (pid 29535)
2022-02-18 15:23:58,739 INFO  Executed systemctl<serv_mapper3>, exit status 0
2022-02-18 15:23:58,740 DEBUG --- test execute
2022-02-18 15:23:58,741 DEBUG EnvironmentC8y Execute
2022-02-18 15:23:58,742 DEBUG --- test validate
2022-02-18 15:23:58,742 DEBUG EnvironmentC8y Validate
2022-02-18 15:23:58,744 DEBUG Process parameters for systemctl<serv_mosq>
  command line : /usr/bin/systemctl status mosquitto
    arg #1     : status
    arg #2     : mosquitto
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mosq.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mosq.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-18 15:23:58,751 DEBUG Waiting up to 600 secs for process systemctl<serv_mosq> (pid 29536)
2022-02-18 15:23:59,057 INFO  Executed systemctl<serv_mosq>, exit status 0
2022-02-18 15:23:59,059 DEBUG Process parameters for systemctl<serv_mapper4>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper4.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper4.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-18 15:23:59,067 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper4> (pid 29537)
2022-02-18 15:23:59,323 INFO  Executed systemctl<serv_mapper4>, exit status 0
2022-02-18 15:23:59,324 INFO  Validate
2022-02-18 15:23:59,325 DEBUG Performing regex contains=True grep on file: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect_c8y.out
2022-02-18 15:23:59,361 WARN  Grep on tedge_connect_c8y.out contains "tedge-agent service successfully started and enabled!" ... failed [run.py:33]
2022-02-18 15:23:59,361 DEBUG Performing regex contains=True grep on file: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect.out
2022-02-18 15:23:59,364 WARN  caught <class 'pysys.exceptions.FileNotFoundException'>: unable to find file "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect.out"
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/basetest.py", line 1203, in assertGrep
    result = getmatches(f, expr, ignores=ignores, returnFirstOnly=(contains==True), encoding=encoding or self.getDefaultFileEncoding(f), flags=reFlags, mappers=mappers)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/utils/filegrep.py", line 59, in getmatches
    raise FileNotFoundException("unable to find file \"%s\"" % (file))
pysys.exceptions.FileNotFoundException: unable to find file "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect.out"
2022-02-18 15:23:59,379 WARN  Grep on tedge_connect.out contains "tedge-mapper-c8y service successfully started and enabled!" failed due to <class 'pysys.exceptions.FileNotFoundException'>: unable to find file "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect.out" ... blocked [run.py:37]
2022-02-18 15:23:59,384 DEBUG --- test cleanup
2022-02-18 15:23:59,384 INFO  
2022-02-18 15:23:59,385 INFO  cleanup:
2022-02-18 15:23:59,385 DEBUG Running registered cleanup function: <bound method EnvironmentC8y.myenvcleanup of <TedgeConnectTestSMServices object at 0x75b166f0>>
2022-02-18 15:23:59,385 DEBUG EnvironmentC8y Cleanup
2022-02-18 15:23:59,479 DEBUG Process parameters for sudo<tedge_disconnect_c8y>
  command line : /usr/bin/sudo /usr/bin/tedge disconnect c8y
    arg #1     : /usr/bin/tedge
    arg #2     : disconnect
    arg #3     : c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_disconnect_c8y.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_disconnect_c8y.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-18 15:23:59,484 DEBUG Waiting up to 600 secs for process sudo<tedge_disconnect_c8y> (pid 29541)
2022-02-18 15:24:01,756 INFO  Executed sudo<tedge_disconnect_c8y>, exit status 0
2022-02-18 15:24:01,759 DEBUG Process parameters for systemctl<serv_mapper5>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper5.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper5.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-18 15:24:01,768 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper5> (pid 29583)
2022-02-18 15:24:02,073 INFO  Executed systemctl<serv_mapper5>, exit status 3
2022-02-18 15:24:02,074 DEBUG ProcessUser cleanup function done.
2022-02-18 15:24:02,077 INFO  
2022-02-18 15:24:02,078 INFO  Test duration: 23.85 secs
2022-02-18 15:24:02,079 INFO  Test final outcome:  BLOCKED
2022-02-18 15:24:02,079 INFO  Test outcome reason: Grep on tedge_connect.out contains "tedge-mapper-c8y service successfully started and enabled!" failed due to <class 'pysys.exceptions.FileNotFoundException'>: unable to find file "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect.out" (+1 other failures)
2022-02-18 15:24:02,080 INFO  
