2022-02-25 16:00:09,629 INFO  ==============================================================
2022-02-25 16:00:09,630 INFO  Id:    tedge_connect_test_sm_services
2022-02-25 16:00:09,631 INFO  Dir:   tedge_connect/
2022-02-25 16:00:09,631 INFO  Title: Validate Software Management Services started and enabled on tedge connect c8y
2022-02-25 16:00:09,632 DEBUG Execution order hint: 0.0
2022-02-25 16:00:09,632 INFO  ==============================================================
2022-02-25 16:00:09,635 DEBUG EnvironmentC8y Setup
2022-02-25 16:00:09,635 INFO  EnvironmentC8y Setup
2022-02-25 16:00:09,636 DEBUG Process parameters for systemctl<serv_mapper1>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper1.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper1.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-25 16:00:09,641 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper1> (pid 32366)
2022-02-25 16:00:09,946 INFO  Executed systemctl<serv_mapper1>, exit status 3
2022-02-25 16:00:10,029 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 3 seconds
2022-02-25 16:00:10,030 INFO  Delaying execution by 8 seconds
2022-02-25 16:00:18,045 DEBUG Process parameters for sudo<tedge_connect_c8y>
  command line : /usr/bin/sudo /usr/bin/tedge connect c8y
    arg #1     : /usr/bin/tedge
    arg #2     : connect
    arg #3     : c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect_c8y.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect_c8y.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-25 16:00:18,054 DEBUG Waiting up to 600 secs for process sudo<tedge_connect_c8y> (pid 32371)
2022-02-25 16:00:28,144 INFO  Executed sudo<tedge_connect_c8y>, exit status 0
2022-02-25 16:00:28,147 DEBUG Process parameters for sudo<tedge_connect_c8y_test>
  command line : /usr/bin/sudo /usr/bin/tedge connect c8y --test
    arg #1     : /usr/bin/tedge
    arg #2     : connect
    arg #3     : c8y
    arg #4     : --test
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect_c8y_test.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect_c8y_test.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-25 16:00:28,153 DEBUG Waiting up to 600 secs for process sudo<tedge_connect_c8y_test> (pid 32472)
2022-02-25 16:00:28,508 INFO  Executed sudo<tedge_connect_c8y_test>, exit status 0
2022-02-25 16:00:28,509 DEBUG Process parameters for systemctl<serv_mosq2>
  command line : /usr/bin/systemctl status mosquitto
    arg #1     : status
    arg #2     : mosquitto
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mosq2.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mosq2.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-25 16:00:28,514 DEBUG Waiting up to 600 secs for process systemctl<serv_mosq2> (pid 32478)
2022-02-25 16:00:28,768 INFO  Executed systemctl<serv_mosq2>, exit status 0
2022-02-25 16:00:28,769 DEBUG Process parameters for systemctl<serv_mapper3>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper3.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper3.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-25 16:00:28,774 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper3> (pid 32479)
2022-02-25 16:00:29,029 INFO  Executed systemctl<serv_mapper3>, exit status 0
2022-02-25 16:00:29,030 DEBUG --- test execute
2022-02-25 16:00:29,031 DEBUG EnvironmentC8y Execute
2022-02-25 16:00:29,031 DEBUG --- test validate
2022-02-25 16:00:29,032 DEBUG EnvironmentC8y Validate
2022-02-25 16:00:29,033 DEBUG Process parameters for systemctl<serv_mosq>
  command line : /usr/bin/systemctl status mosquitto
    arg #1     : status
    arg #2     : mosquitto
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mosq.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mosq.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-25 16:00:29,038 DEBUG Waiting up to 600 secs for process systemctl<serv_mosq> (pid 32480)
2022-02-25 16:00:29,294 INFO  Executed systemctl<serv_mosq>, exit status 0
2022-02-25 16:00:29,296 DEBUG Process parameters for systemctl<serv_mapper4>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper4.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper4.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-25 16:00:29,301 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper4> (pid 32481)
2022-02-25 16:00:29,605 INFO  Executed systemctl<serv_mapper4>, exit status 0
2022-02-25 16:00:29,606 INFO  Validate
2022-02-25 16:00:29,607 DEBUG Performing regex contains=True grep on file: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect_c8y.out
2022-02-25 16:00:29,612 DEBUG Grep on input file tedge_connect_c8y.out successfully matched expression "tedge-agent service successfully started and enabled!" with line: 'tedge-agent service successfully started and enabled!\n'
2022-02-25 16:00:29,613 INFO  Grep on input file tedge_connect_c8y.out ... passed
2022-02-25 16:00:29,614 DEBUG Performing regex contains=True grep on file: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect.out
2022-02-25 16:00:29,618 WARN  caught <class 'pysys.exceptions.FileNotFoundException'>: unable to find file "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect.out"
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/basetest.py", line 1203, in assertGrep
    result = getmatches(f, expr, ignores=ignores, returnFirstOnly=(contains==True), encoding=encoding or self.getDefaultFileEncoding(f), flags=reFlags, mappers=mappers)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/utils/filegrep.py", line 59, in getmatches
    raise FileNotFoundException("unable to find file \"%s\"" % (file))
pysys.exceptions.FileNotFoundException: unable to find file "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect.out"
2022-02-25 16:00:29,666 WARN  Grep on tedge_connect.out contains "tedge-mapper-c8y service successfully started and enabled!" failed due to <class 'pysys.exceptions.FileNotFoundException'>: unable to find file "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect.out" ... blocked [run.py:37]
2022-02-25 16:00:29,671 DEBUG --- test cleanup
2022-02-25 16:00:29,671 INFO  
2022-02-25 16:00:29,672 INFO  cleanup:
2022-02-25 16:00:29,672 DEBUG Running registered cleanup function: <bound method EnvironmentC8y.myenvcleanup of <TedgeConnectTestSMServices object at 0x75c56150>>
2022-02-25 16:00:29,673 DEBUG EnvironmentC8y Cleanup
2022-02-25 16:00:29,748 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 10 seconds
2022-02-25 16:00:29,749 INFO  Delaying execution by 1 seconds
2022-02-25 16:00:30,752 DEBUG Process parameters for sudo<tedge_disconnect_c8y>
  command line : /usr/bin/sudo /usr/bin/tedge disconnect c8y
    arg #1     : /usr/bin/tedge
    arg #2     : disconnect
    arg #3     : c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_disconnect_c8y.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_disconnect_c8y.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-25 16:00:30,761 DEBUG Waiting up to 600 secs for process sudo<tedge_disconnect_c8y> (pid 32487)
2022-02-25 16:00:32,877 INFO  Executed sudo<tedge_disconnect_c8y>, exit status 0
2022-02-25 16:00:32,880 DEBUG Process parameters for systemctl<serv_mapper5>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper5.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/serv_mapper5.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-25 16:00:32,887 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper5> (pid 32523)
2022-02-25 16:00:33,192 INFO  Executed systemctl<serv_mapper5>, exit status 3
2022-02-25 16:00:33,193 DEBUG ProcessUser cleanup function done.
2022-02-25 16:00:33,196 INFO  
2022-02-25 16:00:33,196 INFO  Test duration: 23.57 secs
2022-02-25 16:00:33,198 INFO  Test final outcome:  BLOCKED
2022-02-25 16:00:33,199 INFO  Test outcome reason: Grep on tedge_connect.out contains "tedge-mapper-c8y service successfully started and enabled!" failed due to <class 'pysys.exceptions.FileNotFoundException'>: unable to find file "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_sm_services/Output/linux/tedge_connect.out"
2022-02-25 16:00:33,200 INFO  
