<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="docker_plugin_remove" skipped="0" tests="1" time="4.97" timestamp="2022-04-21T14:34:18">
	<testcase classname="DockerPluginRemoveTest" name="docker_plugin_remove">
		<failure message="BLOCKED: sudo&lt;docker_run&gt; returned non-zero exit code 125" type="BLOCKED"/>
		<system-out>14:34:13 INFO  ==============================================================
14:34:13 INFO  Id:    docker_plugin_remove
14:34:13 INFO  Dir:   plugin_docker/
14:34:13 INFO  Title: Validate docker plugin remove
14:34:13 INFO  ==============================================================
14:34:14 INFO  Executed sudo&lt;docker_images&gt;, exit status 0
14:34:14 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_remove/Output/linux/docker_images.out ... passed
14:34:16 WARN  Executed sudo&lt;docker_run&gt;, exit status 125
14:34:16 INFO  Contents of docker_run.err: 
  Unable to find image 'registry:latest' locally
  docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
  See 'docker run --help'.
  -----

14:34:16 WARN  sudo&lt;docker_run&gt; returned non-zero exit code 125 ... blocked 
14:34:16 WARN  Aborted test due to BLOCKED outcome
14:34:16 INFO  
14:34:16 INFO  cleanup:
14:34:16 INFO  Removing containers scheduled to be cleaned up: ['', '']
14:34:17 WARN  Executed sudo&lt;containers_for_cleanup&gt;, exit status 1
14:34:17 INFO  Removing images scheduled to be cleaned up: ['registry', 'registry', 'registry:2.7.1']
14:34:18 INFO  Executed sudo&lt;containers_for_cleanup&gt;, exit status 0
14:34:18 INFO  
14:34:18 INFO  Test duration: 4.97 secs
14:34:18 INFO  Test final outcome:  BLOCKED
14:34:18 INFO  Test outcome reason: sudo&lt;docker_run&gt; returned non-zero exit code 125
14:34:18 INFO  
</system-out>
	</testcase>
</testsuite>
