2022-02-04 16:43:17,277 INFO  ==============================================================
2022-02-04 16:43:17,278 INFO  Id:    tedge_connect_test_negative
2022-02-04 16:43:17,278 INFO  Dir:   tedge_connect/
2022-02-04 16:43:17,279 INFO  Title: Validate tedge connect c8y --test (negative case)
2022-02-04 16:43:17,279 DEBUG Execution order hint: 0.0
2022-02-04 16:43:17,280 INFO  ==============================================================
2022-02-04 16:43:17,283 DEBUG --- test execute
2022-02-04 16:43:17,283 INFO  Execute `tedge connect c8y --test`
2022-02-04 16:43:17,284 DEBUG Process parameters for sudo<tedge_connect_c8y_test_negative>
  command line : /usr/bin/sudo /usr/bin/tedge connect c8y --test
    arg #1     : /usr/bin/tedge
    arg #2     : connect
    arg #3     : c8y
    arg #4     : --test
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_negative/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_negative/Output/linux/tedge_connect_c8y_test_negative.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_negative/Output/linux/tedge_connect_c8y_test_negative.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-04 16:43:17,289 DEBUG Waiting up to 600 secs for process sudo<tedge_connect_c8y_test_negative> (pid 907)
2022-02-04 16:43:17,594 INFO  Executed sudo<tedge_connect_c8y_test_negative>, exit status 1
2022-02-04 16:43:17,595 DEBUG --- test validate
2022-02-04 16:43:17,595 INFO  Validate
2022-02-04 16:43:17,596 DEBUG Performing regex contains=True grep on file: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_connect/tedge_connect_test_negative/Output/linux/tedge_connect_c8y_test_negative.err
2022-02-04 16:43:17,603 DEBUG Grep on input file tedge_connect_c8y_test_negative.err successfully matched expression "Error: failed to test connection to Cumulocity cloud." with line: 'Error: failed to test connection to Cumulocity cloud.\n'
2022-02-04 16:43:17,604 INFO  Grep on input file tedge_connect_c8y_test_negative.err ... passed
2022-02-04 16:43:17,609 DEBUG --- test cleanup
2022-02-04 16:43:17,610 DEBUG ProcessUser cleanup function done.
2022-02-04 16:43:17,611 INFO  
2022-02-04 16:43:17,612 INFO  Test duration: 0.34 secs
2022-02-04 16:43:17,613 INFO  Test final outcome:  PASSED
2022-02-04 16:43:17,613 INFO  
